### ISSUE TITLE
Merge bracing-related linters into one

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1009]
Follow-up to https://github.com/r-lib/lintr/issues/1002#issuecomment-1080330707

There are several linters related to bracing that could all be merged into one (possible with options to toggle which rule to apply, though they're all default linters, so that may not be so helpful).

We'll also need to mark any old linters as deprecated. Therefore this is important to include with 3.0.0.

**Comment by AshesITR** [comment]
While working on this issue:
The wording of the function linter should be changed to "should" instead of "must":

```
Any function spanning multiple lines must use curly braces.
```

**Comment by MichaelChirico** [comment]
Dup of #1041
