### ISSUE TITLE
#937 breaks trailing commas with `lintr::lint_dir` (undocumented behavior)

### ISSUE THREAD

**Issue by bersbersbers** [r-lib/lintr#1027]
I have the impression #937 prevents the use of a trailing comma in `lint_dir`, as in `lintr::lint_dir(path=".",)`, which is possible in v2.0.1. Is that something that was intented; foreseen and accepted; or unintended and worthy of fixing?

_Originally posted by @bersbersbers in https://github.com/r-lib/lintr/issues/937#issuecomment-1081544675_

**Comment by MichaelChirico** [comment]
I think it was working unintendedly before. I'd like to make the update back-compatible with a deprecation warning if possible, but I don't really see how to do so.

Closing for now, but PRs welcome. Ideally very concise -- I don't think it's worth adding too much code complexity to support this either.
