### ISSUE TITLE
Export flatten_lints or have lint_files function that accepts multiple files

### ISSUE THREAD

**Issue by JSchoenbachler** [r-lib/lintr#1030]
I was wondering if there was any possibility that one of the two things in the title can happen. As it is, if I want to lint multiple files that are not in the same directory, I currently have to construct a list of the files, iterate over them and create a list of lint results, then use the (unexported) `flatten_lints` function to flatten them in a way they can be used to populate the markers tab. Here is a snippet of code I use currently:
```
library('foreach')
fileList = list.files('./', recursive = TRUE)
fileList = fileList[grepl('\\.R$', fileList)]
lintsFound = foreach(file = fileList) %do% {
  lint(file)
}
lintsFound = lintr:::flatten_lints(lintsFound)
```
Like I said, it's not much code so simply exporting `flatten_lints` would probably be sufficient, but I thought it might not hurt to also have a function that mirrors `lint_dir` except you provide a vector of files instead of a directory. What are your thoughts?

**Comment by AshesITR** [comment]
This seems like you want `lint_dir()` but run in parallel? Related to #240 in that case.

**Comment by MichaelChirico** [comment]
Oh, just saw this again! I just wrote this up in a bit more detail in #2135, let's continue discussion there.
