### ISSUE TITLE
Local List in Vim get populated with temporary files locations when using ALE 

### ISSUE THREAD

**Issue by wfmueller29** [r-lib/lintr#1035]
Hi,

I love using lintr. However, when using lintr within Vim, the linter errors get written to temporary files in addition to the file where the error was found. So when trying to quickly index through the linting errors using the local list in Vim, I will be prompted to open buffers for each temporary file. I am using the ALE plugin to enable asynchronous linting. 
![image](https://user-images.githubusercontent.com/25310357/161177771-ca219055-73dc-44b3-bdc6-0d5e4bd11607.png)

I have read both the ALE and lintr documentation,  but I definitely could be missing something. This happens both on windows and on mac. Thank you for the awesome linting package. It is super useful. Any help would be appreciated.

**Comment by IndrajeetPatil** [comment]
@jimhester, @MichaelChirico, @AshesITR Anyone amongst you uses Vim? Or can we tag anyone who does to help us either confirm or resolve the issue?

**Comment by MichaelChirico** [comment]
emacs 🙋‍♂️

**Comment by AshesITR** [comment]
I use PyCharm.

**Comment by jimhester** [comment]
I use vim, but not ale.

@wfmueller29 could you provide a minimal vimrc that exhibits the behavior you describe?

**Comment by IndrajeetPatil** [comment]
I am going to close this because there hasn't been a response from OP, and the issue also seems outdated at this point.

We can reopen it if there are any further updates.
