### ISSUE TITLE
Refactor semicolon_terminator_linter for consistency?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1040]
`semicolon_terminator_linter` strikes me as a bit "off" w.r.t. the style elsewhere in the package

 1. The name `semicolon_linter` seems better to me
 2. The signature `function(semicolon = c("compound", "trailing"))` looks odd. I think we are aligning more on toggling these types of things with `allow*`-style arguments, e.g. `function(allow_compound = FALSE, allow_trailing = FALSE)` would be equivalent to the current signature.

Are either of these worth doing?

Of course, we can use a deprecation cycle to make the changes more gradually.

**Comment by AshesITR** [comment]
Sounds good to me. We can use the major release to do the renaming and deprecate the old function, pointing to `semicolon_linter()` with the appropriate arguments in the deprecation message.
