### ISSUE TITLE
Allow other packages to register the set of default linters

### ISSUE THREAD

**Issue by jimhester** [r-lib/lintr#105]
This would allow a user to simply `library(lintrStyleGoogle)` or `library(lintrStyleBioconductor)` and have the default linters be switched to google or Bioconductor style.

This would also make it fairly easy for users to extend existing styles I think.

**Comment by MichaelChirico** [comment]
@AshesITR I think this is already sufficiently handled by `linters_with_tags()`, WDYT?

**Comment by AshesITR** [comment]
I think it is by the `packages` argument. You can now even configure whether you want to combine the linters or just pick default linters from another package.
