### ISSUE TITLE
Anonymous function syntax

### ISSUE THREAD

**Issue by sgvignali** [r-lib/lintr#1054]
When I lint a file containing the new syntax for an anonymous function like in the following example:

`apply(x, 1, \(i) sqrt(sum(i^2)))`

I get the following message:

`Place a space before a left parenthesis, except in a function call`

Is it possible to deactivate this check?

**Comment by MichaelChirico** [comment]
agree it's a bug, thanks!

**Comment by MichaelChirico** [comment]
Hi @sgvignali I actually don't get your error on the development version -- please install from this repo for now.

```
lintr::lint("apply(x, 1, \\(i) sqrt(sum(i^2)))\n", lintr::spaces_left_parentheses_linter())
```
