### ISSUE TITLE
Location of the lintr cache

### ISSUE THREAD

**Issue by jennybc** [r-lib/lintr#1062]
@jimhester and I got this email from Kurt Hornik / CRAN.

> This has
>
>   ./lintr/R/zzz.R:    cache_directory = "~/.R/lintr_cache",   
>
> in violation of the CRAN Policy: can you please change to use
> tools::R_user_dir("lintr", "cache") instead?
>
> CC'ing Jennifer for devtools: this has
>
> ./devtools/man/lint.Rd:The lintr cache is by default stored in
>  \verb{~/.R/lintr_cache/}
>
> which will need to be changed accordingly ...

I'm relaying since I'm not sure how often Jim is checking in on lintr. But it sounds like it may be time to change the default location of lintr's cache. boxr recently did something similar and there's a discussion of the new location [starting around here in this issue thread](https://github.com/r-box/boxr/issues/219#issuecomment-1048274673).

**Comment by jimhester** [comment]
Using `tools::R_user_dir()` or the equivalent in backports if we want to maintain older R compatibility seems reasonable.

The email didn't say anything about a timeframe for an update, @AshesITR and @MichaelChirico, how close are we to the next release? Can we wait for that or do we need to do a patch release to address this issue?

**Comment by MichaelChirico** [comment]
Hmm I think if pressed we could probably turn around a release in 1-2 weeks, WDYT @AshesITR?

There's more than could be finished in that timeframe in the milestone https://github.com/r-lib/lintr/milestone/2 but we could triage some of that away for a 3.0.1, e.g. Otherwise we are looking at 1-2 months I think.

**Comment by AshesITR** [comment]
I think we should push for releasing 3.0.0 soon. Even the current development version has gone a long way from 2.0.1 to the point I'm using the GitHub version in prod.
