### ISSUE TITLE
Update vignettes

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#1122]
Make sure the vignettes `using_lintr.Rmd` and `creating_linters.Rmd` reflect the current APIs and best practices.

**Comment by AshesITR** [comment]
`using_lintr.Rmd` needs only a few changes which I made in #1120.
`creating_linters.Rmd` needs to get updates:

 * use new style of roxygen tags for documenting linters
 * change variable name to `source_expression`
 * maybe promote XPath linters
 * introduce the checker functions once they are added in #1073 
 * update the PR URL to r-lib

**Comment by MichaelChirico** [comment]
> A good example of a simple linter is the `assignment_linter`.

not anymore 😅

**Comment by AshesITR** [comment]
`equals_na_linter` is currently the smallest with a direct XPath implementation by lines of code.
