### ISSUE TITLE
Export `xml_nodes_to_lint()`?

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#1124]
Used in most linters by now, because it's a very useful helper for XPath-based linting.
Since we already export `with_id` and `ids_with_token` as helpers for the parse data based approach, I think we could also export `xml_nodes_to_lint()`.

Also thinking about the function name: Shouldn't this be either vectorized (on nodesets or lists of nodes) or singular (`xml_node_to_lint()`)?

cc @MichaelChirico

**Comment by MichaelChirico** [comment]
SGTM-- had the same thought about vectorizing.

(PS I just moved so it will take me a bit to get things in order and get back to he review/PR queue)

**Comment by MichaelChirico** [comment]
Assigning this to me -- I have a branch in progress already
