### ISSUE TITLE
conjunct_stopifnot_linter could be generalized (in particular, to include assert_that)

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1131]
`assertthat::assert_that()` falls under basically the same lens as `conjunct_stopifnot_linter()` -- code like

```
assertthat::assert_that(A && B)
```

is usually more informative if tested separately:

```
assertthat::assert_that(A)
assertthat::assert_that(B)
```

(similar proviso applies if `msg=` argument is used as for the named test version of `stopifnot()`).

raising now since this generalization is best served by renaming the function, so we might want to do that before 3.0.0 -- we don't have to implement the new logic yet, just to land on a name if we decide to include the `assert_that` case.

**Comment by AshesITR** [comment]
Maybe `conjunct_assertion_linter()`?

**Comment by MichaelChirico** [comment]
that sounds good to me

**Comment by MichaelChirico** [comment]
Perils of not actually reading the source :facepalm: 

this is already done at HEAD:

https://github.com/r-lib/lintr/blob/57f150ab691257f3207d0460764e9793306c5ae9/R/conjunct_test_linter.R#L1-L14

Measure twice, cut once I guess :)
