### ISSUE TITLE
Improve documentation for default_undesirable_functions

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1133]
Currently I don't see any reasoning behind why the various default undesirables are considered undesirable.

Inspired by this SO Q:

https://stackoverflow.com/questions/65466324/why-are-sapply-and-options-undesirable

**Comment by AshesITR** [comment]
We could document those either in the lint itself (e.g. `use lapply() or vapply() because they are type-stable.`) or document in `?default_undesirable_functions`. WDYT?

**Comment by MichaelChirico** [comment]
I think both would be good. In the lint is better for users, in the docs for developers.

**Comment by AshesITR** [comment]
The message is currently hard-coded to be "Function {fun} is undesirable. As an alternative, {explanation}".
So explaining the reasoning in the lints would require refactoring the generated message.
Any idea for a good "format" for the new messages?

Maybe simply "Function {fun} is undesirable. {explanation}"?

**Comment by MichaelChirico** [comment]
It can be similar to our deprecation note, right? old / new / explanation?

**Comment by AshesITR** [comment]
That would make the old interface (named character vector) impossible to use for customization.

**Comment by MichaelChirico** [comment]
right... in that case your suggestion is the best we can do I think. (I always found the old pattern to restrictive anyway)

**Comment by AshesITR** [comment]
Fixed in #1149
