### ISSUE TITLE
`lint_package`: Include R Markdown templates

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/lintr#1134]
I've authored a couple of R packages that have R Markdown templates defined in `rmarkdown/templates/<TEMPLATE_NAME>/skeleton/skeleton.Rmd`. Automatic linting of these files during a `lint_package()` call would be awesome. I'm open to working on a pull request, but any assistance with this would be much apppreciated!

**Comment by mjsteinbaugh** [comment]
Additionally, automatic linting of R Markdown formatted vignettes inside of `vignettes` would be helpful as well.

**Comment by AshesITR** [comment]
Hi, can you test the current development version? #447 was fixed since 2.0.1 has been released.
If it doesn't lint the files you mention, this would be a bug.

**Comment by AshesITR** [comment]
Interpreting the thumbs up as "confirmed fixed".
Feel free to re-open if there is still an issue.
