### ISSUE TITLE
undesirable_operator_linter: optionally allow some usages of `:::`

### ISSUE THREAD

**Issue by bersbersbers** [r-lib/lintr#1143]
When developing a package (let's say `pack`), I see no problem referencing private functions using `pack:::` as that is fully under my control. This may be the case, for example, when wrapping a Shiny app in a package and having some `app.R` consisting solely of `shinyApp(pack:::shiny_ui(), pack:::shiny_server)`. Other valid uses may be `testthat` test scripts which are usually run standalone and in which you would like to reference some private code that you also have in the package, without duplicating it. (I may be overlooking a better way to achieve these things.)

**Comment by AshesITR** [comment]
You can use the `op` argument of undesirable_operator_linter to customize this.

A concrete way to avoid `:::` in your usecase might be to do it like shinyWidgets does it, i.e., export a function that constructs and runs the shiny app from within the package.

**Comment by bersbersbers** [comment]
> You can use the `op` argument of undesirable_operator_linter to customize this.

That means disabling `:::` altogether, correct? At the price of missing unintended uses of `ggplot2:::plot_dim` and the like.

> A concrete way to avoid `:::` in your usecase might be to do it like shinyWidgets does it, i.e., export a function that constructs and runs the shiny app from within the package.

Yes, exporting functions such as `shiny_ui` and `shiny_server` might the best way in fact. I will have to note in the docs that these are not part of the public/stable API then.

Thanks for the feedback, and feel free to close this issue :)

**Comment by AshesITR** [comment]
> > You can use the `op` argument of undesirable_operator_linter to customize this.
> 
> 
> 
> That means disabling `:::` altogether, correct? At the price of missing unintended uses of `ggplot2:::plot_dim` and the like.
> 

Yes, sorry, I misunderstood that.
Disabling the operator just for some packages would require a new configuration option. Not sure how useful that is.

> 
> > A concrete way to avoid `:::` in your usecase might be to do it like shinyWidgets does it, i.e., export a function that constructs and runs the shiny app from within the package.
> 
> 
> 
> Yes, exporting functions such as `shiny_ui` and `shiny_server` might the best way in fact. I will have to note in the docs that these are not part of the public/stable API then.
> 

If the `app.R` is also shipped with the package, maybe there is a way to write it such that you can export a stable function?
Otherwise, I'd favor a `# nolint: undesirable_operator.` to exporting internal functions.

> 
> Thanks for the feedback, and feel free to close this issue :)

Leaving open for now in case this feature request interests more users.

**Comment by MichaelChirico** [comment]
FWIW it should be pretty straightforward to implement a customized linter for your use case. I would take more convincing to support exceptions for the lintr version.

**Comment by bersbersbers** [comment]
> Otherwise, I'd favor a `# nolint: undesirable_operator.` to exporting internal functions.

I knew I would be getting good advice here :) yes, https://github.com/r-lib/lintr/issues/605 is very valuable here indeed.
