### ISSUE TITLE
Always populate xml_parsed_content and full_xml_parsed_content (perhaps with xml_missing)

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1147]
Just confirmed that

```
xml2::xml_find_all(xml2::xml_missing, "//a")
# {xml_nodeset (0)}
```

so most of our linters will just work with the replacement.

Unfortunately

```
xml2::xml_find_first(xml2::xml_missing, "//a")
```

is an error, so we may have to guard the code against attempting `xml_find_first()` on missing documents.

**Comment by AshesITR** [comment]
We could add a test case with an all-empty document to verify on `linters_with_tags(tags = NULL)`?
