### ISSUE TITLE
lint() doesn't work without lintr being attached

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1156]
In a fresh session:

```
lintr::lint("R/exclude.R")
Error in linters_with_defaults(line_length_linter = line_length_linter(120),  : 
  could not find function "linters_with_defaults"
```

That doesn't seem right to me. Do we need to set something in .onLoad?

**Comment by AshesITR** [comment]
That's from reading the settings.
Is there a clean way to temporarily attach lintr during the parse attempt?

**Comment by MichaelChirico** [comment]
Hmm I'm not reproducing it anymore? I tried it a few different times last night... Alas.

**Comment by AshesITR** [comment]
Oh maybe an old version if `lintr` was loaded?

**Comment by MichaelChirico** [comment]
It must've been something like that, and from switching branches around... but i definitely restarted R & reinstalled lintr... must've been something more subtle.
