### ISSUE TITLE
xml_nodes_to_lints' offset= could just be used to land the cursor after the linted symbol?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1163]
In `T_and_F_symbol_linter` and now (#1160) `implicit_integer_linter`, we've got a case where `offset=` is only needed to land the RStudio marker "to the right" of where the lint is hitting, so that the cursor is conveniently where we can type a fix and be done.

For `T_and_F_symbol_linter`, that's easy, because for both cases, we offset by 1 (`T` -> move right by one, `F` -> move right by one).

But for `implicit_integer_linter`, this won't work, because the landed symbols can have variable width (`1` -> move right by one, `10` -> move right by two).

So I think we need a different API for this case than `offset`.

Will a boolean flag suffice? `xml_nodes_to_lint(postposition = TRUE)`? (name?)

That will certainly cover the two use cases we have thus far.

PS, any different thoughts about restricting `ranges[1] <= column_number <= ranges[2]` for this case?

**Comment by AshesITR** [comment]
Sounds good. `marker_after_and = FALSE` maybe?
Impl. would be `column_number <- ranges[2L] <- ranges[2L] + 1L` if it's set to true.

**Comment by MichaelChirico** [comment]
> marker_after_and = FALSE

is that `marker_after_end`?

and SGTM. What about `ranges[1L]`? set to `column_number`?

**Comment by AshesITR** [comment]
> _end

Haha, yes 😅

I would leave ranges[1] alone, unless I'm missing something.

**Comment by MichaelChirico** [comment]
NVM, I was stuck thinking about the old case when `offset<0` is possible which we've now eliminated.
