### ISSUE TITLE
Linters for deprecated features?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1167]
Glancing at the breaking changes part of the NEWS, it looks like a lot (if not most/all) of the code that the update'll break could be detected by a linter.

Should we offer such a linter as part of the release?

**Comment by AshesITR** [comment]
What would the lints be?

**Comment by MichaelChirico** [comment]
https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L7

call to `Lint` with `linter=` argument

https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L9

`lint()`, `lint_dir()`, `lint_package()` with non-`()` linters supplied

https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L10-L16
https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L24

replicate `undesirable_function_linter` for these

https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L20-L22

usages relying on deprecated positional ordering

https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L23

`with_id()`/`ids_with_token()` calls with `source_file=` argument

https://github.com/r-lib/lintr/blob/c34819937c4c5341dfb71ce7dc759e0597bf409c/NEWS.md?plain=1#L25-L26

`undesirable_function_linter()` calls with `return()` included

**Comment by AshesITR** [comment]
Wouldn't most of these usages be in `.lintr` files, which we don't lint?
Not sure if the linter helps that much in addition to the warnings generated by our code.

**Comment by MichaelChirico** [comment]
that's true. I guess I had in mind reverse imports, etc that aren't just using us in CI. and in principle we could offer a script to lint .lintr as well...

but not substantially more helpful than just reading the warnings & our revimports are few. so probably not worth the maintenance burden.

one last point in favor of this is as an example for other packages -- it's not super useful for us but in general offering a deprecated_linter could be a useful idea for other packages.

but anyway, closing for now.
