### ISSUE TITLE
Unknown package 'data.table' in Rd xrefs

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1170]
I'm seeing this intermittently on GHA now... e.g. https://github.com/r-lib/lintr/runs/6540133051?check_suite_focus=true

![image](https://user-images.githubusercontent.com/7606389/169673835-dacec8ad-a630-48f0-b46d-bdbcce4b4ba2.png)

Not sure why it's intermittent -- maybe it relies on an internet connection for `available.packages()`?

Either way, if it's showing up sometimes, it's probably easier to just unlink the non-dependency packages.

**Comment by MichaelChirico** [comment]
Indeed, `tools` is running `utils::available.packages()`:

https://github.com/r-devel/r-svn/blob/d1850cd8f4fc84ee6b7f49ba19c18f828bd8227d/src/library/tools/R/QC.R#L4511-L4528

**Comment by AshesITR** [comment]
Is that reproducible or sporadic?
The links definitely help improve usability of the undesirable functions help...

**Comment by MichaelChirico** [comment]
I might be missing something but IINM all of the failed PR CIs right now are because of this issue

**Comment by AshesITR** [comment]
Ok then they must go.
