### ISSUE TITLE
Package logo

### ISSUE THREAD

**Issue by hadley** [r-lib/lintr#1188]
Do y'all have any ideas for a package logo? I can help get it designed if you have some idea what it might look like

**Comment by AshesITR** [comment]
Thanks for the offer! (see also #981)

I personally like the [SonarLint Logo](https://www.sonarlint.org/logos). Maybe that can serve as an inspiration?
The squiggly line is a good metaphor as it relates to spellchecking.

**Comment by MichaelChirico** [comment]
copying notes from the dup'd issue:

@IndrajeetPatil:
> I love talking about `{lintr}`, but I always find it a tad bit dissatisfying to have slides with just the name of the package without a cool hex sticker to go along with it! 🙃
> 
> I wish I were creative enough to design and contribute one, but maybe this can be crowdsourced (on Twitter, e.g.)?
> 
> Thanks for the awesome work, either way! Looking forward to the `3.0.0` release.

@AshesITR:
> If created, this could also be featured here: https://github.com/GuangchuangYu/hexSticker

**Comment by AshesITR** [comment]
@hadley Do you think this will make it in time for the 3.0.0 release?

**Comment by hadley** [comment]
@AshesITR sorry for dropping the ball on this; probably not.

**Comment by shaopeng-gh** [comment]
@hadley fyi I am working on starter workflow for lintr and it requires a icon/logo, looks like we can put it to use right away when it is ready :)
The required format I need to use is SVG, don't worry at all if your output is PNG I can use free converter to convert it.
(my input is if the logo is text type, the text/font should be clear/large proportion enough when the display size is small as icon, so that user can tell what text it is.)

**Comment by IndrajeetPatil** [comment]
How about this one? Just a suggestion. 

![image](https://user-images.githubusercontent.com/11330453/183625044-a24a9a27-e6e5-4fc1-a166-d3f39bd14dfd.png)

**Comment by hadley** [comment]
@IndrajeetPatil I like the basic idea, but I think it needs to be a dryer (not a washing machine) to convey "lint".

**Comment by hadley** [comment]
Another approach would be do something like a wool jumper (e.g. https://www.shutterstock.com/image-vector/green-sweater-lint-balls-1550178998) with little red wigglies as lint?

**Comment by AshesITR** [comment]
Another idea:

https://www.shutterstock.com/de/image-photo/freisteller-fliege-binder-78825286

Maybe a bow tie could be combined somehow with a red squiggle to indicate good style?

**Comment by AshesITR** [comment]
I like the idea of a lint roller.

**Comment by MichaelChirico** [comment]
I don't have any issue with a lint roller as the baseline, but that one does not look very good to me.

**Comment by IndrajeetPatil** [comment]
I am out of ideas. I think we need a fresh take on the sticker design, preferably by a professional.

**Comment by hadley** [comment]
Here's a proposal from our designer @gregswinehart

![lintr](https://github.com/user-attachments/assets/c35e2752-f0e2-4ec6-b58d-cfbb06914f1f)

**Comment by AshesITR** [comment]
Thanks for the design! I like the idea.
To me the logo feels a bit "high-res".
Is there a way to reduce the contrast / business of the knit texture without losing too much detail?

**Comment by IndrajeetPatil** [comment]
Looks really good, but I personally found the package name text to be quite hard to read.

**Comment by IndrajeetPatil** [comment]
@jimhester Any strong opinions on the proposed logo? 

If not, I'd vote for shipping this logo in the next CRAN release. :)

**Comment by MichaelChirico** [comment]
> To me the logo feels a bit "high-res".

+1 here, it would be great to see how this might look in print

> I personally found the package name text to be quite hard to read.

Just wondering, is that when it's at full resolution, or zoomed all the way out so that it looks roughly hex-sized on your screen? For the latter, `lintr` looks pretty clear to me, but I can see how it might be harder when blown up.

**Comment by jimhester** [comment]
I somehow missed Greg's design, looks pretty great to me

**Comment by gregswinehart** [comment]
Here's a version with the contrast turned down a bit so it's a little more lo-fi.... Also a typical font for the name.

![lintr-v2](https://github.com/user-attachments/assets/893e2524-7ca0-44cc-bdf9-5ce0348b2480)

**Comment by gregswinehart** [comment]
Here are the two options in the context of other hexes for comparison!
![lintr-example-1](https://github.com/user-attachments/assets/6ca77cdc-bcf7-4203-962b-1c4ba9308c4d)
![lintr-example-2](https://github.com/user-attachments/assets/8eb9c679-fb16-4a56-bc68-a31d30591f45)

**Comment by AshesITR** [comment]
Thanks @gregswinehart !

AFAICT the "knitted" look in your composition has a different color (light blue instead of black) for the knit texture in comparison to the earlier proposal.
To me this looks beautiful even on a large scale.

I'd vote for the slightly toned down knit pattern instead of using a regular font for the package name.

**Comment by gregswinehart** [comment]
![lintr-v4](https://github.com/user-attachments/assets/703e9799-4065-44a8-a9d8-104df8fadcf1)
OK!  So I think we might have a consensus on this one? Do I have that right? Thanks so much to all of you for the input.

**Comment by IndrajeetPatil** [comment]
Thanks, @gregswinehart!

Would like to do a PR to add the logo to README? Or would you like us to take care of it? Either way is fine. 😊

**Comment by gregswinehart** [comment]
@IndrajeetPatil No problem, I'll make that PR today!

**Comment by gregswinehart** [comment]
@jimhester (hi Jim!), @IndrajeetPatil, @AshesITR, @Hadley, @MichaelChirico, 

The hex is now in the repo! Thanks all.

**Comment by jimhester** [comment]
Thanks Greg! Logo looks great!
