### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by hadley** [r-lib/lintr#1190]
This just requires someone to run `usethis::git_default_branch_rename()` and then active contributors need to run `usethis::git_default_branch_rediscover()`

**Comment by AshesITR** [comment]
> Error: You don't seem to have admin permissions for the source repo 'r-lib/lintr', which is required to rename the default branch.

**Comment by MichaelChirico** [comment]
looks like we need @jimhester here

**Comment by hadley** [comment]
I can also do it.

**Comment by MichaelChirico** [comment]
ok yes, please do. thanks for taking the initiative! it's been on my mental to-do list for a while

**Comment by hadley** [comment]
Ok, done!
