### ISSUE TITLE
improve source markers for commas_linter

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1215]
Yes, could be done as a follow-up, similar to `spaces_inside_linter`.
Currently, all lints mark the comma, which is fine for spaces before, but useless for spaces after.

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/issues/1214#issuecomment-1136419741_

**Comment by AshesITR** [comment]
WDYT about adding an option to `xml_nodes_to_lints()` to lint whitespace between an `expr` and its `,/following-sibling::*[1]`?
We could refactor the `marker_at_end = FALSE` arg to `marker = c("expr_start", "expr_end", "whitespace_after")` before it hits CRAN.

**Comment by MichaelChirico** [comment]
which linters would that option be used? sounds like we want something more generalizable than that.

**Comment by AshesITR** [comment]
`spaces_inside_linter` and `commas_linter` woud use "whitespace_after".
Maybe allow supplying custom XPaths for range_start, range_end, column_number instead?
Defaults would be `"number(./@col1)"`, `"number(./@col2)"` and `"number(./@col1)"`.
`marker_at_end = TRUE` would translate to `"number(./@col2 + 1)"` -- untested if we can add constants in XPath directly.
