### ISSUE TITLE
Exclusions throwing warning in roxygen documentation

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1219]
Similar to #1193 -- linting throws a warning for unknown linter `linter2_name` here:

https://github.com/r-lib/lintr/blob/c68c11e269bf2b5c15335cbfde163f05734417a9/R/exclude.R#L12

Is skipping `roxygen2 comments the right approach here?

**Comment by AshesITR** [comment]
What if `# nolint: line_length.` is used in a roxygen block?

Maybe better to declare this a false positive since it'll likely only occur in out documentation.

Other option: Use inline R code to emit the `\code` fragment?

**Comment by MichaelChirico** [comment]
> Maybe better to declare this a false positive since it'll likely only occur in out documentation.

agree it's not really relevant for downstreams... but how to do that?

> Other option: Use inline R code to emit the \code fragment?

sorry, not following... `\code{# nolint...}` will still be caught by the exclusions code right?

**Comment by AshesITR** [comment]
No, but some `@evalRd` magic can avoid it 😄

**Comment by MichaelChirico** [comment]
As long as it's only needed in the one place that should be tolerable :) happy to review PR
