### ISSUE TITLE
Drop lint for trailing whitespace after { ?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1220]
As seen here:

https://github.com/r-lib/lintr/blob/c68c11e269bf2b5c15335cbfde163f05734417a9/tests/testthat/test-open_curly_linter.R#L35-L37

But not matched by the new `brace_linter`:

```
lint("a <- function() {  \n}", brace_linter())
```

I think the new behavior is better -- `trailing_whitespace_linter()` is the one designed to lint in this case.

OTOH, `open_curly_linter()` is being marked as deprecated -- is it worth making such a change?

This came up working on #1186. Linting on whitespace also makes it difficult to convert to XPath since the XML tree is unaware of the whitespace.

**Comment by MichaelChirico** [comment]
Realizing it's a bit of a re-hash since we already agreed to drop the trailing whitespace lint for the new `brace_linter()` -- so the question is whether we want to _also_ apply it to `open_curly_linter()`

**Comment by AshesITR** [comment]
Does lintr 2.0.1 produce two lints in the default setting?

If so, fine with changing the deprecated linter.
Otherwise, also fine with `# nolint: cyclocomp.` for this deprecated code.

**Comment by MichaelChirico** [comment]
yes there are two lints:

```
git checkout v2.0.1 && R CMD INSTALL . && R
lintr::lint("function() {  \n}")
<text>:1:12: style: Opening curly braces should never go on their own line and should always be followed by a new line.
function() {  
           ^
<text>:1:13: style: Trailing whitespace is superfluous.
function() {  
            ^~
```
