### ISSUE TITLE
`in_ci()` doesn't include `in_github_actions()`

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#1233]
GHA is also a CI, no?

**Comment by hadley** [comment]
You can also check that the CI env var is set; that's common across many platforms and is what we generally use.

**Comment by hadley** [comment]
It seems like https://github.com/r-lib/lintr/blob/lint-error/R/methods.R#L68-L82 assumes `in_ci()` will return TRUE on GHA.

**Comment by IndrajeetPatil** [comment]
This is no longer relevant (cf. https://github.com/r-lib/lintr/pull/2446).
