### ISSUE TITLE
Avoid do.call(rbind) for backport_linter

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1254]
Can you compare performance to `vapply()` with a conditional `t()` if `length(n_names) == 1L`?
My experience is that `do.call(rbind, ...)` is extremely slow compared to `vapply()`

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/1240#discussion_r882370998_

**Comment by AshesITR** [comment]
Did a test, found a 3ms improvement:

```r
# A tibble: 2 × 13
  expression                                       min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result       memory time           gc              
  <bch:expr>                                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>       <list> <list>         <list>          
1 lapply(exprs$expressions, old_linters[[i]])    123ms    127ms      7.77        NA     15.5     8    16      1.03s <list [401]> <NULL> <bench_tm [8]> <tibble [8 × 3]>
2 lapply(exprs$expressions, new_linters[[i]])    121ms    124ms      7.97        NA     15.9     8    16         1s <list [401]> <NULL> <bench_tm [8]> <tibble [8 × 3]>
```

Do we want to merge that or just leave this as-is?

The new code looks like this:
```r
    all_names_nodes <- xml2::xml_find_all(xml, names_xpath)
    all_names <- xml2::xml_text(all_names_nodes)
    n_names <- length(all_names)
    if (n_names == 0L) {
      return(list())
    }

    needs_backport <- vapply(backport_blacklist, x = all_names, `%in%`, logical(n_names))
    if (n_names == 1L) {
      bad_idx <- any(needs_backport)
    } else {
      needs_backport <- t(needs_backport)
      bad_idx <- colSums(needs_backport) > 0L
    }
```

**Comment by MichaelChirico** [comment]
3ms is basically noise... Is that run on QC.R?

i think advantage of old is `rbind` overhead is pretty fixed/limited -- `length(backport_list)` is pretty small / probably considered constant, whereas the overhead of `t()` is pretty unlimited (depends on `n_names` which could be huge). Readability-wise they're roughly similar (I'd definitely not use `%in%` like that, rather, `vapply(backport_list, function(nm) all_names %in% nm, logical(n_names))`; or maybe the `match` form looks better?), but I lean towards old for avoiding conditional logic.

**Comment by AshesITR** [comment]
yep, it is. with `backports_linter("3.0.0")`.

Closing.
