### ISSUE TITLE
Bug in get_source_expressions(): no xml_missing() returned for failed parse of "\\R"

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1262]
Found thanks to #1255 

```
writeLines(R"("\R")", tmp<-tempfile())
str(get_source_expressions(tmp)$expressions, 2L)
List of 1
 $ :List of 6
  ..$ filename               : chr "/tmp/Rtmpp3pPgq/file7238733fe7f6"
  ..$ file_lines             : Named chr "\"\\R\""
  .. ..- attr(*, "terminal_newline")= logi TRUE
  .. ..- attr(*, "names")= chr "1"
  ..$ content                : Named chr "\"\\R\""
  .. ..- attr(*, "terminal_newline")= logi TRUE
  .. ..- attr(*, "names")= chr "1"
  ..$ full_parsed_content    : NULL
  ..$ full_xml_parsed_content: NULL
  ..$ terminal_newline       : logi TRUE
```

`full_parsed_content` should be `xml_missing()`

**Comment by MichaelChirico** [comment]
issue is `full_parsed_content` is `NULL`, so `is_lint_level` thinks its an expression entry:

https://github.com/r-lib/lintr/blob/cfa2ab798b27bd6868854acbbb2f20c848c908bd/R/is_lint_level.R#L17

But then `spaces_left_parentheses_linter()` attempts to extract `xml_parsed_content` which doesn't exist:

https://github.com/r-lib/lintr/pull/1255/files#diff-8d86e47d9909736bca476d66cb14ab2989004cd79e4e540228b5c027a53ac720R51

**Comment by MichaelChirico** [comment]
So I think it's a bug in `is_lint_level`

**Comment by AshesITR** [comment]
Since `full_xml_parsed_content` is guaranteed to never be `NULL` with the fix to `safe_parse_to_xml()`.
