### ISSUE TITLE
unused_import_linter can never catch glue or rex

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1293]
```
lintr::lint(text = "
library(glue)
library(rex)
1 + 1
",
lintr::unused_import_linter())
```

The problem is the linter finds `glue` and `rex` as symbols inside the `library()` calls, and `glue::glue()` and `rex::rex()` are exported symbols, so it thinks it's found a namespace usage:

https://github.com/r-lib/lintr/blob/558733897d9b7c91d3c4fae497f095a18d124466/R/unused_import_linter.R#L47

We should exclude symbols inside `library()` calls

**Comment by AshesITR** [comment]
Fix should be easy in L27, condition on `not(parent::expr/preceding-sibling::expr[1]/SYMBOL_FUNCTION_CALL[text() = 'library' or text() = 'require'])`

**Comment by MichaelChirico** [comment]
right -- any package that exports its own name as a function.

Technically also something like `pkg` exports `foo`:

```
library(pkg)
library(foo)
foo::bar()
```

(not sure if it's relevant... can't think of an example right away)

**Comment by AshesITR** [comment]
The latter should be fine because we don't capture `SYMBOL_PACKAGE` as a usage.
