### ISSUE TITLE
lint_package() hangs on edgarWebR

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1340]
Found during work on #1304, haven't had a chance to investigate. Also haven't confirmed if the issue is present in 2.0.1.

```
git clone git@github.com:mwaldstein/edgarWebR.git
Rscript -e "lintr::lint_package("edgarWebR")
```

hangs for at least several minutes.

**Comment by MichaelChirico** [comment]
Looks like the issue is this file which contains a dump of a giant object:

https://raw.githubusercontent.com/mwaldstein/edgarWebR/master/tests/cache/browse-edgar-11457c.R

Investigating...

**Comment by MichaelChirico** [comment]
Looks like `commas_linter` is hanging:

```
l = readLines("https://raw.githubusercontent.com/mwaldstein/edgarWebR/master/tests/cache/browse-edgar-11457c.R")
writeLines(l, tmp <- tempfile())
lintr::lint(tmp, lintr::commas_linter())
```

hangs

**Comment by MichaelChirico** [comment]
Looks like `preceding-sibling::*[1]` chokes when encountering 59,000 commas that are all siblings! :flushed:

**Comment by MichaelChirico** [comment]
`paren_body_linter()` is also hanging. It looks like `//expr` is a bad idea -- that file returns 138,000 `<expr>` nodes, but only 28 `<OP-RIGHT-PAREN>` nodes. So better to structure the XPath as `//OP-RIGHT-PAREN`.

**Comment by MichaelChirico** [comment]
@AshesITR this looks like a bug -- shouldn't all these be `@line1=`? now the XPath just looks like:

https://github.com/r-lib/lintr/blob/83cae10367d08ad93b2ec8011c51d9d1c5275e8e/R/paren_body_linter.R#L11-L29

```XPath
//expr[
  @line1 = preceding-sibling::FUNCTION/@line1
  | preceding-sibling::IF/@line1
  | preceding-sibling::WHILE/@line1
  | preceding-sibling::OP-LAMBDA/@line1
  and @col1 = preceding-sibling::OP-RIGHT-PAREN/@col1 + 1
]
|
//expr[
  @line1 = preceding-sibling::forcond/@line1
  and @col1 = preceding-sibling::forcond/OP-RIGHT-PAREN/@col1 + 1
]
```

**Comment by AshesITR** [comment]
That does look like a bug, yes.

**Comment by MichaelChirico** [comment]
Surprised it didn't turn up any false positive/negatives anywhere else though :thinking:

**Comment by MichaelChirico** [comment]
Actually looks like a false negative:

```
lint("
if (cond
        )x
", paren_body_linter())
```

**Comment by MichaelChirico** [comment]
If I understand this correctly:

https://stackoverflow.com/a/36829511/3576984

the old XPath is equivalent to

```XPath
//expr[
  (
    (@line1 = preceding-sibling::FUNCTION/@line1)
    | preceding-sibling::IF/@line1
    | preceding-sibling::WHILE/@line1
    | preceding-sibling::OP-LAMBDA/@line1
  ) and (
    @col1 = (preceding-sibling::OP-RIGHT-PAREN/@col1 + 1)
  )
]
|
//expr[
  @line1 = preceding-sibling::forcond/@line1
  and @col1 = preceding-sibling::forcond/OP-RIGHT-PAREN/@col1 + 1
]
```

[Also `|`](https://www.w3.org/TR/1999/REC-xpath-19991116/#node-sets):

> computes the union of its operands, which must be node-sets.

I don't quite get what `$(equality expression) | $(node condition)` is doing, but I guess it will evaluate to true if anything satisfying `$(node condition)` exists?

**Comment by AshesITR** [comment]
Hmm then maybe the set union takes precedence and it actually works as intended?

Anyway, unless there is a noticeable performance difference, we should use the clearer expression that repeats the `@line1 = ` bit.

**Comment by MichaelChirico** [comment]
Definitely wasn't working :) see new tests (confirmed they were failing on `main` as well as on my previous commit).

Also, the condition shouldn't have been using that test to begin with -- the new XPath looks pretty clear if I do say so myself :smiley:
