### ISSUE TITLE
alternative linters for a different coding style

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/lintr#135]
i’d be especially interested in
- `empty_line_indent_linter` (indent empty lines like surrounding code)
- `no_double_quotes_linter` (use single instead of double quotes)
- `tab_linter` (use one single tab per indentation level)

**Comment by MichaelChirico** [comment]
@flying-sheep as of #844 the package has a lot of non-"tidyverse-style" linters. We should definitely accept more. I don't think we have a good sense yet of what linters do/don't "belong" in `lintr` as opposed to being maintained by downstreams. But happy to review PRs.

**Comment by flying-sheep** [comment]
6 years later, I no longer use R much, but thank you haha
