### ISSUE TITLE
Feature request: include linter name in warnings

### ISSUE THREAD

**Issue by jameslamb** [r-lib/lintr#1357]
## Request

Consider the following code:

```r
library(lintr)
f <- tempfile(fileext = ".R")
writeLines("do_thing <- T", f)
lintr::lint(
    filename = f
    , linters = list(
        "tf" = lintr::T_and_F_symbol_linter
    )
    , cache = FALSE
)
```

On `{lintr}` 2.0.1 installed from CRAN and on the latest version from GitHub (https://github.com/r-lib/lintr/commit/801fac322613121f32ae916af379161a838e3b27, installed with `remotes::install_github("r-lib/lintr")`), this produces the following output (the `(...)` is mine, just to make the path a bit more readable):

```text
(...)/T/RtmpIvPGWZ/fileb817b0f6442.R:1:14: style: Use TRUE instead of the symbol T.
do_thing <- T
            ~^
```

As a user of `{lintr}`, I'd like to see the linter name printed in the output, like this:

```text
(...)/RtmpIvPGWZ/fileb817b0f6442.R:1:14: style: [T_and_F_symbol_linter] Use TRUE instead of the symbol T.
do_thing <- T
            ~^
```

## Motivation

I learned tonight from @MichaelChirico that as of `{lintr}` 3.0.0, it'll be possible to use a comment like the following to say "ignore warnings from a specific linter on this line" (https://github.com/microsoft/LightGBM/pull/5249#discussion_r889447818).

```r
x <- T  # nolint: T_and_F_symbol_linter`
```

I totally see the value in being specific there and would like to do that. But since the linter name isn't printed in the warnings from `lintr::lint()`, figuring out the right value to add in that comment will require some trial-and-error or searching in this package's source code.

## References:

As an example, `flake8` also supports such targeted comments (https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#in-line-ignoring-errors), and I've found it really helpful that it prints in its output exactly the code that should be added to `# noqa` comments.

```shell
echo "x = (1,2,3,y)" > ./out.py
flake8 ./out.py
```

```text
./out.py:1:7: E231 missing whitespace after ','
./out.py:1:9: E231 missing whitespace after ','
./out.py:1:11: E231 missing whitespace after ','
./out.py:1:12: F821 undefined name 'y'
```

Example suppressing one specific warning:

```shell
echo "x = (1,2,3,y)  # noqa: E231" > ./out.py
flake8 ./out.py
```

```text
./out.py:1:12: F821 undefined name 'y'
```

Thanks for your time and consideration!

**Comment by MichaelChirico** [comment]
thanks for filing! indeed the though has crossed my mind a few times but I always forgot to file an issue.

v. important to be able to understand at a glance how to suppress each lint now that we have targeted suppression available

**Comment by AshesITR** [comment]
That's a very reasonable request. So far, I've used `as.data.frame(lints)` to find the linter name, since the data frame contains a column `linter`.

We should also think about other output methods, e.g. GHA comments and RStudio Source Markers

**Comment by MichaelChirico** [comment]
I think for interactive use, as.data.frame() suffices, but not available when running as a plugin or in CI.

easiest to just part of print.lints

**Comment by AshesITR** [comment]
Yep. Note GHA markers aren't made directly by print.lints IIRC.

**Comment by jameslamb** [comment]
thanks so much @AshesITR !!

**Comment by AshesITR** [comment]
Thank you for the suggestion!
