### ISSUE TITLE
Use new parse error condition classes in get_source_expressions()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1359]
As noted in the r-devel NEWS, there are new error condition classes associated with parser errors, intended to make it easier to suss out what went wrong:

https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2022/06/04

That should make it easier for `get_source_expressions()` to work -- instead of (or perhaps in addition to) parsing error messages, we can use the error class.

This is an experimental r-devel feature, so definitely not worth working on before our release.

---

I think they'd still like to hear comments from the lintr team about possible changes.  This is only in R-devel, and it won't be released for 10 months, so there's lots of time to try it out.

_Originally posted by @dmurdoch in https://github.com/r-lib/lintr/issues/959#issuecomment-1146576845_

**Comment by AshesITR** [comment]
We're already doing that, cf. `lint_parse_error`.

All parse errors newly inherit from `"parseError"`. Is something missing?

**Comment by MichaelChirico** [comment]
Well, the news was only from today, so I assume there's _something_ new... but I haven't been able to install r-devel to test it out. Let's just leave this open for now.

**Comment by dmurdoch** [comment]
@AshesITR:  Could you expand on "is something missing"?  Is that asking about a problem with the error class, or just asking Michael why he opened this issue?

**Comment by AshesITR** [comment]
Hi @dmurdoch. I was asking if there is anything left to do on the lintr side regarding this.

From my understanding, all the new error classes have a common superclass `"parseError"`, which we already test for and extract the metadata from if it's present.

**Comment by MichaelChirico** [comment]
Remembering this issue, I see this at HEAD:

https://github.com/r-lib/lintr/blob/51c63e0006ae5b619b3cda27062383cc9ee169fc/R/get_source_expressions.R#L156-L194

I assume there's nothing left to do here, though we could do to add some tests (currently those lines are uncovered). But closing anyway, we can come back to that in a code coverage sweep later.
