### ISSUE TITLE
Add a tag to linters that loadNamespace()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1380]
I think these linters have different enough requirements to warrant their own tag, it would make excluding them simpler for users that can't run `loadNamespace()` reliably in their environment.

**Comment by AshesITR** [comment]
Maybe include all linters that somehow evaluate user input?
Would also be useful to partially lint untrusted sources.

`evaluating_linters`?

**Comment by MichaelChirico** [comment]
SGTM. Added to milestone.

**Comment by MichaelChirico** [comment]
BTW, inspired by thinking of how to make this snippet more robust:

https://github.com/r-lib/lintr/blob/1834009999d6e2d1527cffbe2f04a95c54e147a4/.dev/compare_branches.R#L318

So we should use the new tag there when updating
