### ISSUE TITLE
Lint if (FALSE) / while (FALSE) snippets through commented_code_linter?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1428]
Such code is _effectively_ commented code, right?

**Comment by IndrajeetPatil** [comment]
Yeah, I agree that this will be more suitable for inclusion in `unreachable_code_linter()`.

`if (FALSE)` or `while (FALSE)` is a valid use in Roxygen comments for examples that shouldn't be run during CRAN checks. But this shouldn't be an issue since (IINM) we don't lint Roxygen comments anyway.

**Comment by MichaelChirico** [comment]
> if (FALSE) or while (FALSE) is a valid use in Roxygen comments

Disagree btw -- that's what `\dontrun{}` is for :)
