### ISSUE TITLE
Link to R Packages chapter in vignette seems to be broken

### ISSUE THREAD

**Issue by sschmutz** [r-lib/lintr#1460]
This is the line of the vignette document which links to a non-working website:
https://github.com/r-lib/lintr/blob/75d4d3116107f33f258ff6c0eeb8a65464888fa1/vignettes/lintr.Rmd#L55

Instead https://r-pkgs.org/package-structure-state.html I believe it should now be https://r-pkgs.org/structure.html.

**Comment by IndrajeetPatil** [comment]
Thanks for notifying us about this!

https://github.com/r-lib/lintr/pull/1461 should fix it.
