### ISSUE TITLE
Is it possible to avoid repetition across code and docs for undesirable linters?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1464]
Currently, we are repeating the same text twice:

Once in docs-

https://github.com/r-lib/lintr/blob/1a567f09cee74f5eb264a19dfde78f68d8e82278/R/zzz.R#L51

The other time in code-

https://github.com/r-lib/lintr/blob/1a567f09cee74f5eb264a19dfde78f68d8e82278/R/zzz.R#L101-L102

This means that we run the risk of forgetting to update one if the other is updated.

Can we think of a way to avoid this repetition?

**Comment by IndrajeetPatil** [comment]
Not completely sure yet, but there _might_ be a hint about a possible approach in [this](https://github.com/r-lib/roxygen2/pull/1402) PR.

**Comment by AshesITR** [comment]
Maybe a helper like `rd_tags()` can be written that would auto generate the roxygen docs from `all_undesirable_functions`.
