### ISSUE TITLE
Linting a project with custom functions

### ISSUE THREAD

**Issue by franperic** [r-lib/lintr#1465]
I get this error:
` [object_usage_linter] no visible global function definition for ‘apply_config’`

`apply_config` is a custom function defined in a different script.

**Background Information**
In a shiny project, we use custom functions throughout the shiny code.
We are about to implement pre-commit hooks including lintr.

What is the best practice when using custom functions?

Creating a custom package containing all relevant functions would be a solution. But this will take a while to implement and our stakeholders are not ready to invest the needed time.

Furthermore, if you have just a few custom functions it does not make sense to create a package for them. 

I don't want to deactivate the lintr for this script.

How can we cope with this?

**Comment by MichaelChirico** [comment]
sounds like the easiest solution is `# nolint`.

how are you loading the custom function from the other script? I am assuming source(). I guess I'm principle it's possible for object_usage_linter to try and find symbols from sourced scripts, though a general solution is very tough indeed 

> if you have just a few custom functions it does not make sense to create a package for them.

I disagree -- nothing wrong with starting a small package. it will allow you to isolate & test logic more easily. Also, I've often found the once a helper package is started, it tends to grow pretty quickly.

**Comment by franperic** [comment]
yes - we load the functions using `source()`.

As a temporary solution, I will use `# nolint`.
I assume the `# nolint` statement will be all over the codebase. Hence, I will propose creating a custom package.
