### ISSUE TITLE
Shouldn't the "lint-changed-files" GHA fail for PRs that add new lints?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1489]
Currently, when working on a PR, the contributor needs to keep manually checking if they have added any new lints. 
Even if they check that they haven't, something might change during code review, and a lint might be added. Now if they forget to re-check, the reviewer needs to point this out, which is additional work for the reviewer.

So I was wondering if we can instead modify the "lint-changed-files" GHA so that it **fails** when any new lints are detected. Build failures will ensure that neither the contributor nor the reviewer will have to do this manually, and it'd be hard to miss the newly introduced lint. WDYT?

**Comment by MichaelChirico** [comment]
absolutely agree about this. maybe it can be an option to set but I think the default should be failure.
