### ISSUE TITLE
Adding examples to documentation of each linter

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1492]
I think docs for each linter should have an examples section with at least one example of code that does produce lint and another that doesn't.

I think the style guide is good to provide the underlying rationale for the lint (provided that the reader actually clicks on that link!), but it doesn't lead to much exploration on the reader's part. Giving concrete examples means that the reader can just copy-paste examples and start toying around with them to see what does and doesn't lint.

Note to self: Make sure all of them follow the style guide, and so use `"` instead of `'`, e.g.

## Progress tracker

 - [x] absolute_path_linter
 - [x] any_duplicated_linter
 - [x] any_is_na_linter
 - [x] assignment_linter
 - [x] backport_linter
 - [x] boolean_arithmetic_linter
 - [x] brace_linter
 - [x] class_equals_linter
 - [x] commas_linter
 - [x] commented_code_linter
 - [x] condition_message_linter
 - [x] conjunct_test_linter
 - [x] consecutive_stopifnot_linter
 - [x] cyclocomp_linter
 - [x] duplicate_argument_linter
 - [x] equals_na_linter
 - [x] expect_comparison_linter
 - [x] expect_identical_linter
 - [x] expect_length_linter
 - [x] expect_named_linter
 - [x] expect_not_linter
 - [x] expect_null_linter
 - [x] expect_s3_class_linter
 - [x] expect_s4_class_linter
 - [x] expect_true_false_linter
 - [x] expect_type_linter
 - [x] extraction_operator_linter
 - [x] fixed_regex_linter
 - [x] function_argument_linter
 - [x] function_left_parentheses_linter
 - [x] function_return_linter
 - [x] ifelse_censor_linter
 - [x] implicit_integer_linter
 - [x] infix_spaces_linter
 - [x] inner_combine_linter
 - [x] lengths_linter
 - [x] line_length_linter
 - [x] literal_coercion_linter
 - [x] missing_argument_linter
 - [x] missing_package_linter
 - [x] namespace_linter
 - [x] nested_ifelse_linter
 - [x] no_tab_linter
 - [ ] nonportable_path_linter
 - [x] numeric_leading_zero_linter
 - [x] object_length_linter
 - [x] object_name_linter
 - [x] object_usage_linter
 - [x] outer_negation_linter
 - [x] package_hooks_linter
 - [x] paren_body_linter
 - [x] paste_linter
 - [x] pipe_call_linter
 - [x] pipe_continuation_linter
 - [x] redundant_equals_linter
 - [x] redundant_ifelse_linter
 - [x] regex_subset_linter
 - [x] semicolon_linter
 - [x] seq_linter
 - [x] single_quotes_linter
 - [x] spaces_inside_linter
 - [x] spaces_left_parentheses_linter
 - [x] sprintf_linter
 - [x] string_boundary_linter
 - [x] strings_as_factors_linter
 - [x] system_file_linter
 - [x] T_and_F_symbol_linter
 - [x] todo_comment_linter
 - [x] trailing_blank_lines_linter
 - [x] trailing_whitespace_linter
 - [x] undesirable_function_linter
 - [x] undesirable_operator_linter
 - [x] unnecessary_lambda_linter
 - [x] unneeded_concatenation_linter
 - [x] unreachable_code_linter
 - [x] unused_import_linter
 - [x] vector_logic_linter
 - [x] yoda_test_linter

**Comment by IndrajeetPatil** [comment]
Need to wait for #1480 to be merged before I can work on this.

**Comment by LukasWallrich** [comment]
This is a great idea. It would be ideal to also have a brief explanation/link for why that check happens - for instance, I do not understand why the `extraction_operator_linter` wants to see [[ rather than $, and can't find details on that in any style guide ...

**Comment by IndrajeetPatil** [comment]
@LukasWallrich Have a look at the new [docs](https://lintr.r-lib.org/dev/reference/extraction_operator_linter.html#details). Hopefully, it's clear why the recommendation is so.

**Comment by MichaelChirico** [comment]
Please don't forget to add a NEWS item of this when it's done :)

**Comment by IndrajeetPatil** [comment]
Will do! :)

**Comment by LukasWallrich** [comment]
> @LukasWallrich Have a look at the new [docs](https://lintr.r-lib.org/dev/reference/extraction_operator_linter.html#details). Hopefully, it's clear why the recommendation is so.

Very helpful explanation, thanks. However, given that `For data frames (and tibbles), irrespective of the size, the [[ operator is slower than $` and that it does not seem to have any advantage for tibbles, I find the unambiguous recommendation a bit odd ... but I guess linting has to be opinionated about trade-offs and emphasize consistency ...

**Comment by MichaelChirico** [comment]
Hi @LukasWallrich, not that `extraction_operator_linter()` is not a default linter, so it's not really a "recommendation". In fact we don't enforce this on ourselves:

https://github.com/r-lib/lintr/blob/main/.lintr_new

This is just an offered linter as some authors may prefer the robustness.

I'm also reminded of my SO question from long, long ago:

https://stackoverflow.com/q/29956250/3576984

While [[ is slower, it tends to be on the sub-millisecond scale. most authors should not be concerning themselves with the efficiency difference.

**Comment by IndrajeetPatil** [comment]
![giphy](https://user-images.githubusercontent.com/11330453/195429038-1623e94a-714e-4be0-990e-2f17311b614f.gif)

**Comment by MichaelChirico** [comment]
Thanks Indrajeet!!! 💪💪💪
