### ISSUE TITLE
How to execute lintr anaylis in Azure pipelines

### ISSUE THREAD

**Issue by priya785467** [r-lib/lintr#1496]

**Comment by jamiegaida** [comment]
Please see if these instructions are helpful.
https://github.com/jamiegaida/AzurePipelineR

**Comment by MichaelChirico** [comment]
@jamiegaida thanks for the link! It looks helpful. Would you mind adding a quick write-up of the Azure approach to the corresponding vignette?

https://github.com/r-lib/lintr/blob/main/vignettes/continuous-integration.Rmd

**Comment by MichaelChirico** [comment]
Closing as insufficient interest. We still welcome any contribution here.
