### ISSUE TITLE
lintr::object_length_linter() does not work in the case of dependencies with no exports

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/lintr#1503]
Test package:

https://github.com/Bisaloo/testwpp

Error: 

> .Error in data.frame(pkg = ns, fun = getNamespaceExports(ns), stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 1, 0

This happens because the wpp2017 package does not export any functions. It only provides data. If I understand correctly, this means that the following line

https://github.com/r-lib/lintr/blob/f6cf291a9b28b8c0bf88928aa5167b0396ad687d/R/namespace.R#L29

will try to create a data.frame with one element in the first column and 0 in the second, hence the error.

**Comment by IndrajeetPatil** [comment]
Thanks for the report, @Bisaloo! Can you try the patch in https://github.com/r-lib/lintr/pull/1506, and see if that solves the issue for you?

**Comment by Bisaloo** [comment]
No, there is now an error in 

https://github.com/r-lib/lintr/blob/f6cf291a9b28b8c0bf88928aa5167b0396ad687d/R/namespace.R#L40

since `nrow(NULL)` is `NULL`

**Comment by IndrajeetPatil** [comment]
Actually, I tried to see if I can recreate the issue locally with your test package, but I can't. At least not with the development version of `{lintr}`. Am I missing something?

<img width="620" alt="Screenshot 2022-08-24 at 22 04 36" src="https://user-images.githubusercontent.com/11330453/186513033-6bb377db-3ba8-4d99-81dd-41b5f8422d63.png">

**Comment by Bisaloo** [comment]
Well, now, I'm very confused :thinking: 

With #1506:

![image](https://user-images.githubusercontent.com/10783929/186612926-fdfd1b04-5e2a-4604-bc46-6074ebd9447e.png)

With the version from `main`

![image](https://user-images.githubusercontent.com/10783929/186613201-9b5f40c1-e801-4211-ab8d-d3af21cc7ff1.png)

**Comment by IndrajeetPatil** [comment]
Hmm, that’s confusing indeed.

Won’t the easiest way to check if this is reproducible be to include the lint GHA workflow in the test package? 

And, of course, to use the development version of `{lintr}`:

```yaml 
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: r-lib/lintr
          needs: lint
```

**Comment by Bisaloo** [comment]
I think to reproduce, you need to install wpp2017. Otherwise, you'll end up on this branch and not reach the code causing the error.

https://github.com/r-lib/lintr/blob/f6cf291a9b28b8c0bf88928aa5167b0396ad687d/R/namespace.R#L21-L23

**Comment by IndrajeetPatil** [comment]
> I think to reproduce, you need to install wpp2017

Thanks for the tip; that was indeed the issue. Sorry for the confusion. Let's see if the patch fixes the issue.

**Comment by IndrajeetPatil** [comment]
#1509 seems to fix the issue: https://github.com/Bisaloo/testwpp/pull/1
