### ISSUE TITLE
trailing_whitespace_linter false positive in .rmd

### ISSUE THREAD

**Issue by Fablepongiste** [r-lib/lintr#1535]
Do not think the trailing_whitespace_linter check should apply to .rmd ? 

rstudio does not on purpose and I think that's correct
[trailing_whitespace_linter ](https://github.com/rstudio/rstudio/issues/6558)

**Comment by MichaelChirico** [comment]
Could you provide an example of code that lints that you think shouldn't?

**Comment by MichaelChirico** [comment]
Please re-open when you can provide a reprex. Thanks!
