### ISSUE TITLE
Consolidate suboptimal usages of `which()` under one linter

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1544]
To lint for instances of `which(x == min(x))` or `which(x == max(x))`, which should be avoided in favour of more efficient `which.min()` or `which.max()`, respectively.

Ref: https://csgillespie.github.io/efficientR/performance.html

<img width="965" alt="Screenshot 2022-09-20 at 15 39 43" src="https://user-images.githubusercontent.com/11330453/191273752-cfaff66e-e86e-4803-9b2f-a337cf7882d7.png">

**Comment by MichaelChirico** [comment]
Great observation!

I would rather name it `which_optimum_linter()`, or combine it with the pending `which_grepl_linter()` from #884 and just call it `which_linter()` more generally

**Comment by MichaelChirico** [comment]
One issue I have here is `which(grepl(.))` could _either_ go under a `which_linter()` umbrella _or_ a `regex_linter()` umbrella.

It's not clear to me how to prefer one or the other.

**Comment by IndrajeetPatil** [comment]
As astutely noted by @AshesITR, the two versions of the code in the original post aren't equivalent and therefore don't make a good candidate for a new linter. Pity.

https://github.com/r-lib/lintr/pull/2684#issuecomment-2492116754
