### ISSUE TITLE
consecutive_stopifnot_linter should include assert_that (and hence be renamed)

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1604]
Similar reasoning for `consecutive_stopifnot_linter()` applies for using `assert_that(); assert_that(); assert_that()`; unless a `message` is specified, it's better to use the `...` and condense to one `assert_that()` call.

This will entail a deprecation cycle for `consecutive_stopifnot_linter()`, so let's align on a name before continuing.

I think `consecutive_assertion_linter()` fits well, but differs from `conjunct_test_linter()` (which also covers `assert_that()` and `stopifnot()`).

`consecutive_test_linter()` sounds more like it would apply to `testthat` functions, so I'm not sold on it.

**Comment by IndrajeetPatil** [comment]
I'd also vote for `consecutive_assertion_linter()`!

**Comment by AshesITR** [comment]
I'm not too worried about renaming since `assert_that()` is basically `stopifnot(all(...))`.

I remember some discussion wrt `coonjunct_assertion_linter()` as a potential name for `conjunct_test_linter()`, but can't remember why we settled on a different name.
