### ISSUE TITLE
Make an exception for `tribble()` in `missing_argument_linter()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1607]
Since the trailing comma is a common pattern that even we ourselves are using in tests.

``` r
library(lintr)

lint(
  text = "tribble(
  ~x,
  1,
)",
  linters = missing_argument_linter()
)
#> <text>:3:4: style: [missing_argument_linter] Missing argument in function call.
#>   1,
#>    ^
```

<sup>Created on 2022-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So, basically, change the default `except` argument from `c("switch", "alist")` to `c("switch", "alist", "tribble")`. WDYT?

**Comment by MichaelChirico** [comment]
The same applies to basically all the tidyverse functions which use `rlang::list2()` under the hood. That's the point of the `allow_trailing` argument for `missing_argument_linter()`.

I don't see a reason to include `tribble` to the default but not other tidyverse functions; better to just use `allow_trailing` IMO.
