### ISSUE TITLE
Publishing a paper in JOSS

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1633]
Currently, we don't have a publication about `{lintr}`, and I would propose that we write a short paper for [Journal of Open Source Software](https://joss.theoj.org/about). _JOSS_ is open source, open access, and peer reviewed, and has no publication fees. If you aren't familiar with _JOSS_, as an example, see the [paper on `{tidyverse}`](https://joss.theoj.org/papers/10.21105/joss.01686). 

If the team has no objections to this, I can work on creating the first draft in the next few months, which can then be polished further by the team. I've already published seven papers in _JOSS_ about other packages and have a fairly good idea on how to write them. But the actual submission (whenever the final draft is ready) will need to be handled by the first or primary author.

WDYT?

**Comment by MichaelChirico** [comment]
I won't have much time to review / edit / co-author, but happy to support how I can.

**Comment by AshesITR** [comment]
Same for me. Happy to chip in a little bit, but can't make large time commitments.

**Comment by AshesITR** [comment]
What Michael said also holds for me.

**Comment by IndrajeetPatil** [comment]
Thanks, both, for clarifying your intended involvement.

I will be happy to do most of the work to get it ready for submission, and can also handle the submission if _JOSS_ allows it They allow only the primary author to submit, and I am assuming Jim will be the primary/first author here with everyone else ordered according to their contributions at the time of submission (?). At any rate, these details are not important while working on the draft.

Once I get a green signal from @jimhester, I will get started.

**Comment by jimhester** [comment]
Sure, if you are willing to put in the work writing the draft we can do it and I would be happy to review and handle the actual submission.

**Comment by IndrajeetPatil** [comment]
Awesome! Thanks, Jim. I will start working on it. :)

**Comment by IndrajeetPatil** [comment]
Review can be followed at 

https://github.com/openjournals/joss-reviews/issues/7171
