### ISSUE TITLE
Add more explanation to `no_tab_linter()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1672]
Currently, [it](https://lintr.r-lib.org/dev/reference/no_tab_linter.html) only states that one should be preferred over the other, but gives no reason as to why. And, no, Richard Hendricks did not make me write this 🙃

<img width="522" alt="Screenshot 2022-10-11 at 16 33 52" src="https://user-images.githubusercontent.com/11330453/195120512-64b67ef9-615d-4e0c-9ec3-73d4d271a603.png">

**Comment by IndrajeetPatil** [comment]
Nothing in the tidyverse style guide about this, either.

**Comment by MichaelChirico** [comment]
right... I think there's a lot of writing on this elsewhere. if anything I'd just add a link pointing to somewhere else rather than reinventing the wheel and writing yet another spaces-v-tabs article :)
