### ISSUE TITLE
fixed_regex_linter could optionally skip special-free strings

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1689]
Some users prefer the conciseness of `grepl("xxx", str)` to `grepl("xxx", str, fixed = TRUE)`.

I can't think of a snappy name for the argument right away :)

**Comment by AshesITR** [comment]
Wouldn't these users just disable the linter?

**Comment by MichaelChirico** [comment]
to clarify I mean grepl("[$]", x) still lints because it uses regex specials. I was thinking running grepl on the string against itself world work
