### ISSUE TITLE
Consider setting allow_colon = TRUE by default for implicit_integer_linter

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1694]
_Originally posted by @IndrajeetPatil in https://github.com/r-lib/lintr/pull/1691#discussion_r994209330_

As mentioned in #1155, I think it `1:10` should not lint by default, but I know @AshesITR felt otherwise.

Leaving this issue open for further comment and we can revisit a while after the next release.

**Comment by IndrajeetPatil** [comment]
@MichaelChirico, @AshesITR Should we resolve this issue before `3.1.1` release?

**Comment by MichaelChirico** [comment]
As long as there's the option & the style guide is itself silent, the default is really up to us maintainers... do you have any input here @IndrajeetPatil?

**Comment by IndrajeetPatil** [comment]
TBH, after mulling over this some more, I don't feel too strongly about the default here. So we can continue to have the same default we currently have.
