### ISSUE TITLE
quotes_linter()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1729]
I think it makes sense to offer a generalized version of `single_quotes_linter()` that allows users to choose `'` as their preferred quoting character. Of course `"` should be the default.

**Comment by IndrajeetPatil** [comment]
This'd be a breaking change because we plan to deprecate `single_quotes_linter()` in favour of something like `quotes_linter(quote = '"')`?

**Comment by MichaelChirico** [comment]
yes
