### ISSUE TITLE
[Feature request] Provide access to linter parameters via `options()`

### ISSUE THREAD

**Issue by wurli** [r-lib/lintr#1769]
For example, if I am working on a package with 3 other people and we want to run `lint_package()` before making pull requests, it's hard to customise an option for all users, e.g. the default width for `line_length_linter()`, without writing helper functions into the package itself.

If it was possible to change default behaviour of linters using `options()` this would be much easier to do for all users, e.g. by setting options in a project's `.RProfile`.

If you think this would be a useful change I'd be happy to make a pull request.

**Comment by IndrajeetPatil** [comment]
I am not sure if I understand what the issue is here.

Why can't you specify your preferences in the `.lintr` config file? For example, in `{lintr}` also changes the default width:

https://github.com/r-lib/lintr/blob/482402da275db0dfa32c4fc3984c40cc2f257b9b/.lintr#L2

**Comment by wurli** [comment]
Aha! I didn't actually know this was possible. This looks like it's suit my needs perfectly so I'll close the issue. Thanks 😄

**Comment by IndrajeetPatil** [comment]
Glad to hear that.

You can read more about the config file here: https://lintr.r-lib.org/dev/articles/lintr.html#configuring-linters
