### ISSUE TITLE
`nonportable_path_linter` should also recognise `fs::path()`

### ISSUE THREAD

**Issue by Moohan** [r-lib/lintr#1771]
I have some code like `fs::path("/dir/sub_dir/file")` which the `nonportable_path_linter` highlights. For this case, `fs::path()` is equivalent to `file.path()`

**Comment by MichaelChirico** [comment]
your path is indeed not portable -- it assumes the path separator is '/'

See the examples for fs::path():

https://fs.r-lib.org/reference/path.html
