### ISSUE TITLE
Fix examples that crash or hang up R session on CRAN machines

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1775]
cf. https://cran.r-project.org/web/checks/check_results_lintr.html

**Comment by AshesITR** [comment]
I don't understand the logs, to me all output seems to be commented code (##D ...)
Do they --run-dontrun on r-devel under windows only?

**Comment by IndrajeetPatil** [comment]
> Do they --run-dontrun on r-devel under windows only?

I am not sure. I reverse-inferred that they must be doing so based on the output. But maybe that's not the case?

---

That said, as I mention in https://github.com/r-lib/lintr/pull/1776, `\donttest` examples are run in [an additional check](https://www.stats.ox.ac.uk/pub/bdr/donttest/) by BDR, and probably `\dontrun` examples are also run in some other checks. 

Therefore, making sure all examples run successfully (or are never run if they are just for illustrative purposes) is a good preventive practice in general. This is currently not true for lintr-main branch, and is remedied in #1776.

**Comment by MichaelChirico** [comment]
I would say it's not likely the case. It seems that's just the particular example that's running when the machine times out -- this looks like a similar issue to that befalling {data.table}, see

https://github.com/Rdatatable/data.table/issues/5507

**Comment by IndrajeetPatil** [comment]
Thanks. That was helpful to read, and I guess there isn't much we can do.

But I still think #1776 is worth considering for the reasons mentioned in the top-level comment in that PR.

**Comment by AshesITR** [comment]
So essentially, some test is too heavy for CRAN-Windows to digest?
Maybe we can gain some insight by profiling our tests to look for slow code...

**Comment by mattdowle** [comment]
No, not really. Here's a snapshot of lintr's results. It shows the same pattern as data.table; i.e. very large Tinstall times on Windows. In fact, yours is even more severe. Tinstall is just installing. It doesn't include tests at all. The trouble is Uwe is incommunicado so all I can do it guess that the CRAN Windows is severely over laden with tasks, it could even be swapping. It would be helpful if you could contact CRAN -- maybe they or Uwe will reply to you. Perhaps they think it is a data.table only problem despite my emails explaining that it isn't.  Contact from other package maintainers might help.

![image](https://user-images.githubusercontent.com/2779998/203870517-4ecbac62-3208-480b-ad4e-3be9b9cdf440.png)

**Comment by IndrajeetPatil** [comment]
> It would be helpful if you could contact CRAN -- maybe they or Uwe will reply to you. Perhaps they think it is a data.table-only problem despite my emails explaining that it isn't. Contact from other package maintainers might help.

@MichaelChirico, @jimhester Would either of you have time and be willing to write to CRAN about this issue?
