### ISSUE TITLE
Introduce `unnecessary_nested_if_linter()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1778]
In the wild ([e.g.](https://github.com/gadenbuie/starwarsdb/blob/b6339df02e2a2394120ddf36d74b746d1f141f33/R/connect.R#L63-L67)), I have seen this pattern multiple times: there are nested `if()` statements, when a single conditional with the right conditional expression would do.

For example, this

``` r
x <- TRUE
y <- TRUE

# actual
if (x) {
  if (y) {
    print(1.1)
  }
}
#> [1] 1.1
```

can be rewritten as:

```r
if (x && y) print(1.1)
#> [1] 1.1
```

<sup>Created on 2022-11-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The benefit is, of course, reduction in complexity and improved readability.

Currently, this doesn't produce a lint:

``` r
library(lintr)

code <- "if (x) {
  if (y) {
    print(1.1)
  }
}"

lint(
  text = code,
  linters = linters_with_tags(NULL)
)
```

<sup>Created on 2022-11-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

---

P.S. Needless to say, this is relevant only if there isn't some additional code in the outer scope. E.g.

```r
if (x) {
  y <- x + y
  if (y) {
    ...
  }
}
```

**Comment by MichaelChirico** [comment]
Here's another one to be wary of edge cases, but again I can't seem to recall why :)
