### ISSUE TITLE
Missing row numbers in available_linters() data frame

### ISSUE THREAD

**Issue by yousefmustafa** [r-lib/lintr#1781]
When available_linters() is saved as a data frame, it has 73 observations/rows, however the last row in the data frame is named as "77". I checked and the following row names are missing from the availabe_linters() data frame: 8, 47, 51, 58. Is there a specific reason why those row names are skipped in available_linters()? Just pointing this out in case it's a bug

**Comment by IndrajeetPatil** [comment]
Haven't looked closely yet, but, it might be due to the deprecated linters.

**Comment by yousefmustafa** [comment]
It's not that big of an issue as I've just been resetting the row names locally to make sure the row number and linter name match each other. I just pointed out the issue in case it had been overlooked. Thanks!

**Comment by AshesITR** [comment]
Is there a specific reason why you are using the row names, or just a curiosity?
Regardless, we should reset the row names on our end - thanks for reporting!

**Comment by yousefmustafa** [comment]
Since you asked why I'm using row names...I'm attempting to make a package in which available_linters() is printed in the console, and then the user can input the row numbers of the specific linters they want to use, and then the package lints based on that input. If the row labels of the available_linters() data frame don't match the actual row indices, then the incorrect linters are selected. I hope my explanation makes sense. It's not the most elegant attempt at using lintr, but it's where I'm at right now. Thanks for the help!

**Comment by AshesITR** [comment]
Sounds cool, thanks for sharing 😊
