### ISSUE TITLE
Request to add "description" of linters to available_linters() data frame

### ISSUE THREAD

**Issue by yousefmustafa** [r-lib/lintr#1782]
I'm trying to code an interactive way of having a user select what linters that want to use by selecting specific linters from the available_linters() data frame. Some linter names are self-explanatory while others are not. Is it possible/worthwhile to add a description column to available_linters()? As an idea, the description could either be the "description" from the documentation for that linter, or if that's too long it could be the "message" column that's generated for that specific linter after running lint() on a script.

If there's a better way of generating the descriptions of the linters through code, please let me know because I've searched but haven't been able to find it. Thanks!

**Comment by AshesITR** [comment]
You could extract info from R help, see this SO post:
https://stackoverflow.com/questions/8918753/r-help-page-as-object

Adding a short description to the linters.csv seems not too worthwhile considering our preferred way is via the help pages (which are heavily interlinked using tags)
