### ISSUE TITLE
Introduce alias for `unneeded_concatenation_linter()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1797]
`unneeded_concatenation_linter()` is the odd duck out here, and it keeps tripping us (and I assume `{lintr}` users) up (e.g. see my edit to [this](https://github.com/r-lib/lintr/issues/1787) issue title).  

``` r
library(lintr)
ns <- sort(getNamespaceExports("lintr"))
cat(ns[startsWith(ns, "unn")], sep = "\n")
#> unnecessary_lambda_linter
#> unnecessary_nested_if_linter
#> unnecessary_placeholder_linter
#> unneeded_concatenation_linter
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Unfortunately, we can't make a breaking change by renaming it, but maybe a good compromise will be to provide an alias? WDYT?

```diff
unnecessary_lambda_linter
unnecessary_nested_if_linter
unnecessary_placeholder_linter
+ unnecessary_concatenation_linter
unneeded_concatenation_linter
```

**Comment by AshesITR** [comment]
How about we rename the implementation and add a deprecated `unneeded_concatenation_linter()` alerting users of the rename?
