### ISSUE TITLE
About deprecation warnings in `get_source_expressions.R`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1858]
`find_line_fun()` and `find_column_fun()` are internal helper functions used here:

https://github.com/r-lib/lintr/blob/c3ec3a1ec7f44eed1f01f66eaa7b9e8d5922b6e3/R/get_source_expressions.R#L478-L479

But if you look at the definition for these functions, they contain deprecation warnings.

https://github.com/r-lib/lintr/blob/c3ec3a1ec7f44eed1f01f66eaa7b9e8d5922b6e3/R/get_source_expressions.R#L535-L554

I am confused by this:

- who these deprecation warnings are for if these are internal functions?
- why do we not see these warnings if we are already using these functions in the codebase?

**Comment by AshesITR** [comment]
They are a relic of an old interface exposed to (custom) linters.

**Comment by MichaelChirico** [comment]
they're being returned as part of the lint() output right? so they are technically public-facing, is my recollection. hence the need for a deprecation cycle starting with 3.0.0.

given that we are already headed for 3.2.0, we might consider incrementing these deprecation warnings to errors, though. OTOH, in terms of pure calendar time, the deprecation is still pretty new.

**Comment by AshesITR** [comment]
3.0.0 has hit CRAN in June of this year and I think we should give the deprecation cycle at least a full year before it moves to the next stage, i.e. error starting around June 2023 and remove another year later.
This would give package authors and users plenty of time to fix their code before we kill it off.

It would be good to signal a standard deprecation warning though (specifically stating that the deprecation started in 3.0.0).

**Comment by MichaelChirico** [comment]
SGTM. Agree that patience is good for this sort of thing, but wanted to be sure it's discussed among maintainers.

**Comment by IndrajeetPatil** [comment]
Thanks for the clarification! 
Yeah, I was confused because the deprecation didn't have any information about from which version they were deprecated, nor is there any information about the said deprecations in the `NEWS` file.

Also, I guess we should move these functions to [`lintr-deprecated.R`](https://github.com/r-lib/lintr/blob/main/R/lintr-deprecated.R) file?

**Comment by AshesITR** [comment]
Sounds like a good idea
