### ISSUE TITLE
Lint repeated `if`/`else if`/ `else` after a certain threshold?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1868]
After a certain point, a block of conditional statements can become quite difficult to read, maintain, and extend further. 

To see what I mean, consider [this](https://github.com/easystats/insight/blob/99987b198878d932a8701a16e58e9fc7813be170/R/get_transformation.R#L47-L70) example from `{insight}`:

```r
if (transform_fun == "identity") {
  out <- list(transformation = function(x) x, inverse = function(x) x)
} else if (transform_fun == "log") {
  out <- list(transformation = log, inverse = exp)
} else if (transform_fun %in% c("log1p", "log(x+1)")) {
  out <- list(transformation = log1p, inverse = expm1)
} else if (transform_fun == "log10") {
  out <- list(transformation = log10, inverse = function(x) NA)
} else if (transform_fun == "log2") {
  out <- list(transformation = log2, inverse = function(x) NA)
} else if (transform_fun == "exp") {
  out <- list(transformation = exp, inverse = log)
} else if (transform_fun == "sqrt") {
  out <- list(transformation = sqrt, inverse = function(x) x^2)
} else if (transform_fun == "power") {
  out <- list(transformation = function(x) x^2, inverse = sqrt)
} else if (transform_fun == "expm1") {
  out <- list(transformation = expm1, inverse = log1p)
} else if (transform_fun == "log-log") {
  out <- list(
    transformation = function(x) log(log(x)),
    inverse = function(x) exp(exp(x))
  )
}
```

The alternative here is to create a look-up table (using a data frame, named vector/list, etc.), which is much easier to read, and importantly, extend - we just need to add another row for every new transformation:

```r
df <- tibble::tribble(
  ~transform_fun, ~out,
  "identity",     list(transformation = function(x) x, inverse = function(x) x),
  "log",          list(transformation = log, inverse = exp),
  "log1p",        list(transformation = log1p, inverse = expm1),
  "log(x+1)",     list(transformation = log1p, inverse = expm1),
  "log10",        list(transformation = log10, inverse = function(x) NA),
  "log2",         list(transformation = log2, inverse = function(x) NA),
  "exp",          list(transformation = exp, inverse = log),
  "sqrt",         list(transformation = sqrt, inverse = function(x) x^2),
  "power",        list(transformation = function(x) x^2, inverse = sqrt),
  "expm1",        list(transformation = expm1, inverse = log1p),
  "log-log",      list(transformation = function(x) log(log(x)), inverse = function(x) exp(exp(x)))
)
```

---

That said, I am not sure where to draw the line, i.e., how many repeats of `if` + `else if` is too many. Maybe this can be configurable?

Also, note that this is a different linter from any of the existing or proposed ones:

- nested `ifelse()`
- redundant `ifelse()`
- deeply nested conditionals (#1848)

That said, IINM, it does have some overlap with Google's `IfSwitchLinter()`.

**Comment by MichaelChirico** [comment]
Related thing I've been meaning to write some linting for eventually (not sure if it can be subsumed here too):

```r
if (x == "a") {
  # code that doesn't overwrite x
}
if (x == "b") {
  # code that doesn't overwrite x
}
```

can be collapsed to an if/else. the part where we also have to test if the condition variable is changing makes it tough.

**Comment by MichaelChirico** [comment]
See #2304 for the initial implementation of a related linter.

**Comment by IndrajeetPatil** [comment]
Closed by https://github.com/r-lib/lintr/pull/2304
