### ISSUE TITLE
Linting spaces around infix operators that shouldn't have spaces 

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1883]
As mentioned in the style [guide](https://style.tidyverse.org/syntax.html#infix-operators), some infix operators should never be surrounded by spaces:

<img width="722" alt="Screenshot 2023-01-01 at 23 40 57" src="https://user-images.githubusercontent.com/11330453/210186593-399bce91-783f-4e49-9b52-f1035a5f498c.png">

Currently, this is not enforced by any linter:

``` r
library(lintr)

lint(
  text = "x ^ y",
  linters = all_linters()
)

lint(
  text = "x : y",
  linters = all_linters()
)
```

<sup>Created on 2023-01-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

FWIW, `{styler}` enforces this style:

``` r
styler::style_text("x ^ y")
#> x^y
styler::style_text("x : y")
#> x:y
```

<sup>Created on 2023-01-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelChirico** [comment]
The description of this issue is broader than #104, but that issue has a decent discussion already. So marking this as duplicate in favor of the more fleshed-out issue, though subsuming #104 as being fulfilled by this issue might make more sense usually.
