### ISSUE TITLE
Document "symbols" naming style in object_name_linter 

### ISSUE THREAD

**Issue by hedsnz** [r-lib/lintr#1924]
The [documentation](https://github.com/r-lib/lintr/blob/main/R/object_name_linter.R) for `object_name_linter` describes:

> ... The default naming styles are "snake_case" and "symbols".

After that, there is no explanation of what "symbols" means, and there is no example that uses `styles = "symbols"`. Could this documentation please be added?

Thanks

**Comment by luma-sb** [comment]
I was recently asked by my team what the `"symbols"` style for `object_name_linter`  linter did - so did some digging and hit same issue as you @hedsnz . Appears this was introduced to resolve issue #615 which provides helpful examples to demonstrate applicable cases.

**Comment by AshesITR** [comment]
Not sure where to document the regexes, but I would describe `"symbols"` as function names containing only non-alphanumeric characters, e.g., `` `%+%` `` from ggplot2 or `` `%>%` `` from magrittr.
