### ISSUE TITLE
Documentation bug for improvement: customizing the number of spaces for tabs

### ISSUE THREAD

**Issue by parvizfarnia** [r-lib/lintr#1930]
Hello everyone

**My environment:**
```
OS: Windows 11 (64 bits)
R version: 4.2.2 (2022-10-31 ucrt)
Emacs version: 28.2
lintr version: most recent version from Github

```
Based on #1929 I was advised to file a documentation bug for improvement. I am quite beginner both in `Github` and `Lintr`, therefore I wasn't sure whether here was the right place to post this topic.

**Problem description**:
Currently, the default settings in `Lintr` for tabs is 2 spaces instead of 4 spaces which is the global configuration in my Emacs. Based on what I was told in #1929, apparently by adding a hidden file named `.lintr` in my `$HOME` directory (that would be `Roaming` in `Windows 11`) I'll be able to change the default settings to my desired values, something like 

```
linters: linters_with_defaults(
    line_length_linter(120), 
    commented_code_linter = NULL
    . . . 
  )

```
Now, the problem is that so far, I have not managed to find the specific `linter` allowing to specify 4 spaces for tabs. I have checked the following: 

- [Available linters](https://lintr.r-lib.org/reference/linters.html)
- [Using lintr](https://lintr.r-lib.org/articles/lintr.html)
- [Lintr package documentation PDF on CRAN](https://cran.r-project.org/web/packages/lintr/lintr.pdf)

So far, the only linter that I have found about tabs, is [No tab linter](https://lintr.r-lib.org/reference/no_tab_linter.html), but nothing for allowing 4 spaces for tabs instead of 2.

Therefore, I would like to ask, is it me who doesn't know how to read the available documentation properly or the information that I am looking for, is actually missing in the current documentation?

I would appreciate if you could kindly make some clarification as I'm really confused about how to solve this 4-spaces for tabs issue in my new Emacs/Ess installation.

Thanks in advance.

**Comment by MichaelChirico** [comment]
it's in the lint message:

> [indentation lintr] : Indentation should be 2 spaces but is 4 spaces.

(I suspect that's not an exact copy-paste, it should read 'indentation_linter')

the links you sought were indeed the right place to look in general, but they are aligned to the CRAN release.

You're on the development version, so they won't be helpful for cutting-edge features.

instead, you should use available_linters() to see what's available at run time. the package index page within R should also list a help page for all linters currently installed.

**Comment by parvizfarnia** [comment]
According to you, is the syntax of my `.lintr` file (at least) correct?

**Comment by AshesITR** [comment]
I think R interprets the "Documents" directory as HOME by default, you can check `normalizePath("~")` to see where R defines HOME.
