### ISSUE TITLE
Lint *\.[rR] files in exec folder on `lint_package`

### ISSUE THREAD

**Issue by jmaspons** [r-lib/lintr#1947]
As per https://cran.r-project.org/doc/manuals/R-exts.html#Package-subdirectories:

> Subdirectory exec could contain additional executable scripts the package needs, typically scripts for interpreters such as the shell, Perl, or Tcl. NB: only files (and not directories) under exec are installed (and those with names starting with a dot are ignored), and they are all marked as executable (mode 755, moderated by ‘umask’) on POSIX platforms.

I use this folder to save R scripts in my half-project / half-package directories.

I can do the PR if you like

**Comment by MichaelChirico** [comment]
> I can do the PR if you like

Yes please!
