### ISSUE TITLE
Drop deprecated linters from individual tag pages

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1956]
Currently, we surface linters that may be deprecated on the tag descriptions' pages, e.g.

https://github.com/r-lib/lintr/blob/fb294ccca4267c5b6530c7be886ebcdd34afec41/man/style_linters.Rd#L45

This is not ideal since users may attempt to use these without realizing they're deprecated if it's referenced on the tag page without context.

We could either annotate `(deprecated)` on the tag page, or simply omit these from the tag page.

I would opt for the latter.

There are two options:

 1. Amend the code generating the pages to skip if `deprecated` is among the tags
 2. Retain only the `deprecated` tag for such linters

We may still want to keep the tags recorded in inst/lintr/linters.csv for reference (it's still correct metadata about the linter), hence I lean towards option 1 on the assumption it's only a line or two of difference to implement it.

**Comment by AshesITR** [comment]
How do tidyverse packages handle deprecated functions regarding this?
If we only remove the linter from the tag page, there will still be links from the deprecated linter to its tags.
Do the help pages also link to replacements?

**Comment by MichaelChirico** [comment]
> How do tidyverse packages handle deprecated functions regarding this?

Using {lifecycle}, I think mostly [`lifecycle::badge()`](https://lifecycle.r-lib.org/reference/badge.html), e.g. `tidyr::spread()`:

https://github.com/tidyverse/tidyr/blob/0764e65fad777b71aa2a81ffd5447d04a61f8d5e/R/spread.R#L4

> Do the help pages also link to replacements?

Here's what I see at HEAD in `?single_quotes_linter`:

```
     These functions have been deprecated from lintr.

        • ‘open_curly_linter()’ and ‘closed_curly_linter()’ check that
          open and closed curly braces are on their own line unless
          they follow an else, a comma, or a closing bracket.
          Deprecated in favor of ‘brace_linter()’.

        • ‘paren_brace_linter()’ checks that there is a space between
          right parentheses and an opening curly brace. E.g.,
          ‘function(){}’ doesn't have a space, while ‘function() {}’
          does. Deprecated in favor of ‘brace_linter()’.

        • ‘semicolon_terminator_linter()’ checks that no semicolons
          terminate expressions. Deprecated in favor of
          ‘semicolon_linter()’.
```

> If we only remove the linter from the tag page, there will still be links from the deprecated linter to its tags.

not really -- the `lintr-deprecated` page doesn't list tags, and the `linters` page won't list the deprecated linters. Their tags are retained in `inst/lintr/linters.csv` for reference / can be seen through `available_linters(tags = NULL)`.
