### ISSUE TITLE
Refactor `quotes_linter()` to avoid using `with()`

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#1995]
Found here: https://github.com/r-lib/lintr/pull/1993#pullrequestreview-1508688684

codetools has a hard time correctly analyzing the function, causing multiple false positive lints that need to be disabled.
If we refactor `quotes_linter()` to not use `with()`, codetools should have such a hard time analyzing it.

**Comment by MichaelChirico** [comment]
I would be against making the code harder to read on account of a false positive lint. `# nolint` is appropriate for cases like this.

If the proposed refactor would improve readability, then do proceed.

**Comment by AshesITR** [comment]
There already is one, cf. https://gitlab.com/luke-tierney/codetools/-/issues/6, reported 7 months ago.
Not sure why we missed the nolint comments.
