### ISSUE TITLE
Add tryCatch to the defaults for missing_argument_linter()?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2000]
```r
tryCatch(
  foo(x),
  warning = ,
  error = \(cond) stop("Failed!\n", conditionMessage(cond))
)
```

Is perfectly fine for me. I would include `tryCatch()` as a default to `except=`, any other thoughts?

**Comment by AshesITR** [comment]
Does this fall-through also work for `withCallingHandlers()`?

**Comment by MichaelChirico** [comment]
Oops, I got my wires crossed. `tryCatch()` doesn't support this API (and neither does `withCallingHandlers()`) 🤦
