### ISSUE TITLE
Lintr messages not displaying correctly on windows (R studio 2023.06.01 Build 524 -R 4.2.2 -lintr 3.0.2)

### ISSUE THREAD

**Issue by sidd-2203** [r-lib/lintr#2037]
Does somebody know how to fix it?
![image](https://github.com/r-lib/lintr/assets/75191039/e905b224-8730-4743-a1a5-fcb336a3a49c)

**Comment by AshesITR** [comment]
Hi, are you using a custom `.lintr` config?
If so, please provide it so we can see if it contains any issues.
Also, can you try the current development version of lintr using `remotes::install_github("r-lib/lintr")`?

**Comment by sidd-2203** [comment]
It worked!, Thanks
