### ISSUE TITLE
Keep shared internal constants in a central location

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2048]
I was looking around for such a file, seems we don't have one yet. Would apply to other internal constants as well, e.g.

https://github.com/r-lib/lintr/blob/bb7669afa4b90843e8358397e60d02e2fc512953/R/expect_type_linter.R#L76

https://github.com/r-lib/lintr/blob/bb7669afa4b90843e8358397e60d02e2fc512953/R/object_name_linter.R#L1

Follow-up, or I'll make that sweep in this PR?

_Originally posted by @MichaelChirico in https://github.com/r-lib/lintr/pull/2046#discussion_r1285082348_

---

As usual the only trouble is naming (for the file). 'aaa.R' and 'constants.R' are the natural choices, any other thoughts/suggestions?

**Comment by AshesITR** [comment]
They could also go in `zzz.R` because they are only needed at runtime so collation doesn't matter.
