### ISSUE TITLE
line_length_linter() message should mention the current line length

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2057]
This can be helpful to tell at a glance how wide the line is, e.g. in contexts where we don't have our handy IDE ruler visible, we can often guess how to split up the line based on if it's just a few or many characters too long.

I'd also get some mileage out of it while linting our own package -- when running `lint_package(linters = all_linters())`, the default of 80 characters applies --> many false positives, we could filter those out if we could subset on the message being >= 120 instead. This is not the proper way to handle this problem, but would be handy in interactive situations.

**Comment by AshesITR** [comment]
FWIW the usecase, as you mentioned, is better served by `linters_with_tags(NULL, line_length_linter(120L))`.
