### ISSUE TITLE
filter_and: New linter, or part of `conjunct_test_linter()`?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2073]
One linter for #884 looks for `dplyr::filter(x, A && B)` and recommends `dplyr::filter(x, A, B)`.

Should this be a new linter (we call it `filter_and_condition_linter()`, but I think `conjunct_filter_linter()` would fit the {lintr} style better), or be subsumed as part of the existing `conjunct_test_linter()`?

**Comment by AshesITR** [comment]
Seems like a good place to me.
