### ISSUE TITLE
literal_coercion_linter fails when deparse1() is unavailable

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [r-lib/lintr#2097]
Error message:
<samp>
Error: Linter 'literal_coercion_linter' failed in [...redacted...].R: could not find function "deparse1"
</samp>

`deparse1()` requires either {backports} v1.1.7 or R 4.0.0

https://github.com/r-lib/lintr/blob/720c18e020cf68d7e2096f1cb22dca881b1afe40/R/literal_coercion_linter.R#L110

**Comment by MichaelChirico** [comment]
nice catch! the fix should be pretty easy, do you want to take a stab at a PR?
