### ISSUE TITLE
`seq_linter()` should recommend `.I` for `1:.N`

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2101]
BTW if this is data.table code, it should be `rev(.I)`.
Not correct in general, though, so the current message is fine I think.

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2099#discussion_r1310816164_

**Comment by MichaelChirico** [comment]
Confirming `seq_len(.N)` is exactly how `.I` is defined:

https://github.com/Rdatatable/data.table/blob/4c633907a651f25a4e02c86e6bebb6f5c8c37fa8/R/data.table.R#L1348

**Comment by AshesITR** [comment]
I noticed there is an interaction with `by=`:

``` r
library(data.table)
df <- data.table(grp = rep(c("a", "b"), each = 2L), val = rep(c(1L, 2L), times = 2L))
df[, rx := .I, by = .(grp)][rx > 1, val := 0L]
df
#>    grp val rx
#> 1:   a   1  1
#> 2:   a   0  2
#> 3:   b   0  3
#> 4:   b   0  4
df <- data.table(grp = rep(c("a", "b"), each = 2L), val = rep(c(1L, 2L), times = 2L))
df[, rx := seq_len(.N), by = .(grp)][rx > 1, val := 0L]
df
#>    grp val rx
#> 1:   a   1  1
#> 2:   a   0  2
#> 3:   b   1  1
#> 4:   b   0  2
```

<sup>Created on 2023-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelChirico** [comment]
🤦 I really should know better

https://github.com/Rdatatable/data.table/issues/1206

In that case let's just close the issue. `seq_len(.N)` will always work.
