### ISSUE TITLE
Add a Parameter to commas_linter to Allow Comma Followed by Closing Bracket Without Space

### ISSUE THREAD

**Issue by MEO265** [r-lib/lintr#2102]
Currently, the commas_linter marks an expression like `x[1,]` as incorrect, expecting a space after the comma. This is because the default behavior enforces a space after each comma in an expression. However, there is a common convention, where a comma followed directly by a closing bracket does not necessitate a space. This writing style is even utilized in the official base R documentation, specifically in the matrix section.

To cater to this, I propose adding a new parameter to the commas_linter function which allows users to specify whether a comma followed immediately by a closing bracket should be marked as incorrect or not. For instance:

`commas_linter(allow_trailing_comma = TRUE)`

When `allow_trailing_comma` is set to `TRUE`, commas_linter would not mark `x[1,]` as incorrect.

**Comment by AshesITR** [comment]
Nice idea. Noting the the default should be `FALSE`, though, since we try to line up our defaults with the tidyverse styleguide.

https://style.tidyverse.org/syntax.html#commas

A PR is welcome if you'd like to give it a try.

**Comment by MEO265** [comment]
> Nice idea. Noting the the default should be `FALSE`, though, since we try to line up our defaults with the tidyverse styleguide.
> 
> https://style.tidyverse.org/syntax.html#commas
> 
> A PR is welcome if you'd like to give it a try.

I have incorporated the change on my end and was just about to update the tests when I noticed that there are no tests for false positive events for the `commas_linter` yet, which would be the main change brought about by the parameter. Do you have rules for how I can best test that something is not being linted?
