### ISSUE TITLE
Detection of while(TRUE) and while(FALSE) 

### ISSUE THREAD

**Issue by MEO265** [r-lib/lintr#2106]
t would be handy to introduce a new linter that detects `while(TRUE)` constructs and suggests adopting `repeat` for clearer infinite loop indication. In the same linter, a feature could be developed to identify `while(FALSE)` constructs, signaling unreachable code or potentially as an additional feature of the existing `unreachable_code_linter`.

**Comment by MichaelChirico** [comment]
the latter is #1428. the former should be a new linter, yes
