### ISSUE TITLE
any_is_na_linter() should throw for NA %in% x

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2113]
_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2112#pullrequestreview-1614583357_

**Comment by MEO265** [comment]
Maybe we should also lint `c(NA, y) %in% x` to encourage `anyNA(x) & y %in% x`

**Comment by MichaelChirico** [comment]
There are definitely hits on GitHub, though not a ton:

https://github.com/search?q=lang%3AR+%2F%5B%5Ea-z0-9._%5DNA%28_%28integer%7Creal%7Ccomplex%7Ccharacter%29_%29%3F%5Cs*%5B%25%5D%28ch%29%3Fin%5B%25%5D%2F&type=code

Note there are false positives in the search because GH search cannot be made case-sensitive AFAIK.
