### ISSUE TITLE
implicit_assignment_linter() misses assignments in later arguments of calls

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2136]
```r
lintr::lint("foo(a, x <- y)\n", lintr::implicit_assignment_linter())
```

**Comment by MichaelChirico** [comment]
@IndrajeetPatil shouldn't this lint?

https://github.com/r-lib/lintr/blob/8ac582ce048282269eb8caa96327e509318329c4/tests/testthat/test-implicit_assignment_linter.R#L94

Operator precedence means this is equivalent to

```r
map(.x = 1:4, .f = x <- (~.x+1))
```

It makes sense to me that the version where the mapper is doing assignment shouldn't lint:

```r
map(.x = 1:4, .f = ~(.x+1 -> x))
```

**Comment by MichaelChirico** [comment]
This also looks out of place:

https://github.com/r-lib/lintr/blob/8ac582ce048282269eb8caa96327e509318329c4/tests/testthat/test-implicit_assignment_linter.R#L245

If it's meant not to lint, shouldn't `with_options()` be part of the default `except=` instead?

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil shouldn't this lint?
> 
> https://github.com/r-lib/lintr/blob/8ac582ce048282269eb8caa96327e509318329c4/tests/testthat/test-implicit_assignment_linter.R#L92-L95
> 
> Operator precedence means this is equivalent to
> 
> ```r
> map(.x = 1:4, .f = x <- (~.x+1))
> ```
> 
> It makes sense to me that the version where the mapper is doing assignment shouldn't lint:
> 
> ```r
> map(.x = 1:4, .f = ~(.x+1 -> x))
> ```

I am still not sure why this should lint with implicit assignment linter because there is no assignment inside a function call here. If anything,  `object_usage_linter()` will produce a lint here for unused `x` variable. 

If the issue is about operator precedence, I feel like this should be covered under a different linter? Am I missing something?

**Comment by MichaelChirico** [comment]
the linked test (lines 92-95) does have a top-level assignment in a call -- the .f argument is `` `<-`(x, ~.x+1)``

**Comment by IndrajeetPatil** [comment]
I am still confused. I thought the lambda syntax for anonymous function creates a function that is passed as argument. 
So, in the function call `map()`, the second argument being passed is the anonymous function, and not ``  `<-`(x, ~.x+1) `` assignment inside that anonymous function. Am I mistaken about that?

``` r
identical(
  purrr::map(
    .x = 1:4,
    .f = ~ .x + 1 -> x
  ),
  purrr::map(
    .x = 1:4,
    .f = function(.x) .x + 1 -> x
  )
)
#> [1] TRUE
```

<sup>Created on 2023-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelChirico** [comment]
after the ~ example `x` will exist in the calling environment; not so after the function one.
