### ISSUE TITLE
Handle unused variables with `glue` (Variation of #352)

### ISSUE THREAD

**Issue by thothal** [r-lib/lintr#2162]
This is a variation of issue #352 which still produces 

> `[object_usage_linter] local variable 'x' assigned but may not be used`

```r
library(glue)
test <- function() {
  x <- 1
  msg <- "{x}"
  glue(msg)
}
```

Reprex:

```r
library(lintr)
expect_lint("library(glue)\ntest <- function() {\n  x <- 1\n  msg <- \"{x}\"\n  glue(msg)\n}", 
            NULL, 
            object_usage_linter())
```

**Comment by MichaelChirico** [comment]
That's out of scope for {lintr}. It's a can of worms to try and detect and evaluate dynamic variables like `msg`. In simple cases like your example, just write `glue("{x}")`; more generally, this is a perfect case for using `# nolint`. More complicated cases become close to impossible to evaluate statically.
