### ISSUE TITLE
Should `redundant_*()` linters be renamed to `unnecessary_*()` for consistency?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#2198]
Follow-up on https://github.com/r-lib/lintr/issues/1797

``` r
library(lintr)

linter_names <- names(all_linters())

linter_names[grepl("^redundant|^unnecessary", linter_names)]
#> [1] "redundant_equals_linter"          "redundant_ifelse_linter"         
#> [3] "unnecessary_concatenation_linter" "unnecessary_lambda_linter"       
#> [5] "unnecessary_nested_if_linter"     "unnecessary_placeholder_linter"
```

<sup>Created on 2023-09-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
Of course, we would follow the same deprecation process we followed [before](https://github.com/r-lib/lintr/pull/1862).

**Comment by MichaelChirico** [comment]
I think they're not interchangeable. I would not do this without stronger motivation.

**Comment by IndrajeetPatil** [comment]
You mean the terms _redundant_ and _unnecessary_ are not interchangeable here?

With regard to the motivation, in addition to the naming consistency, I think this change also increases discoverability (“tab completion”-friendly) of all linters related to unnecessary code. But I can understand if that does not feel like strong enough of a motivation.

**Comment by MichaelChirico** [comment]
I think the way to increase discoverability is with a shared tag
