### ISSUE TITLE
Use {cli}, not {crayon}

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2220]
https://github.com/r-lib/lintr/blob/87b59571f1430b937f4282344a9e3712866e21da/DESCRIPTION#L39

{crayon} is superseded by {cli}:

https://github.com/r-lib/crayon/blob/f11f6e66df40513ca07b241eb986e058f91fff33/README.md?plain=1#L2-L7

**Comment by IndrajeetPatil** [comment]
I was also going to suggest this. 

In fact, I would suggest that we should use it to format most of our conditions. 

I will be happy to work on this.

**Comment by MichaelChirico** [comment]
> In fact, I would suggest that we should use it to format most of our conditions.

That sounds good, but I'll suggest two work streams: (1) to just replace our {crayon} usage (2) to work in {cli} more generally

**Comment by MichaelChirico** [comment]
Although, the latter workstream implies upgrading {cli} from Suggests to Imports. Less sure about that.

**Comment by IndrajeetPatil** [comment]
FWIW, it is already a hard dependency of `{lintr}`, though:

``` r
"cli" %in% tools::package_dependencies("lintr", recursive = TRUE)[[1]]
#> [1] TRUE
```

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

via `{cyclocomp}`:

```r
pak::pkg_deps_explain("lintr", "cli")
#> intr -> cyclocomp -> desc -> cli 
```

**Comment by MichaelChirico** [comment]
Got it. I missed it since my {desc} (1.4.0) doesn't have that dependency. {cli} was added to {desc} 1.4.1.
