### ISSUE TITLE
Enforce use of `call. = FALSE` in `stop()` and `warning()`

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/lintr#2222]
This is part of the official tidyverse guidelines: https://design.tidyverse.org/err-call.html.

Some people might prefer to display the call but we should at least ensure that use of `call.` is consistent throughout the package. So an argument like `display_call` defaulting to `FALSE` might be helpful.

Before I start working on this, I wanted to double check there is not already an issue or work in progress for this that I missed.

**Comment by Bisaloo** [comment]
Although I struggle a bit to reconcile the guideline in two tidyverse documents:

- https://style.tidyverse.org/error-messages.html#error-location says

> Ideally the error message should mention the failing function call.

- https://design.tidyverse.org/err-call.html

> Don’t display the call when generating an error message. Either use `stop(call. = FALSE)` or [`rlang::abort()`](https://rlang.r-lib.org/reference/abort.html) to avoid it.

**Comment by AshesITR** [comment]
I think the intention is to not pollute the traceback with the actual call to `stop()`.
