### ISSUE TITLE
Should design.tidyverse.org be authoritative for defaults?

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#2229]
> Since it's part of the style guide

Is it? The 'design' book is not the style guide... the latter AFAICT is mum on the topic. Would help to know if we intend to enforce both the style guide and the design guide by default (what does {styler} do here @lorenzwalthert?)

_Originally posted by @MichaelChirico in https://github.com/r-lib/lintr/pull/2226#issuecomment-1747253870_

**Comment by MichaelChirico** [comment]
{styler} does not enforce the design guide:

https://github.com/r-lib/lintr/pull/2226#issuecomment-1747550787

So neither should we (by default). We could add related linters under a `design` tag.

**Comment by Bisaloo** [comment]
Note about history and consistency: 

Another linter based on the design guide is [`function_argument_linter()`](https://github.com/r-lib/lintr/blob/main/R/function_argument_linter.R), and it's indeed not tagged with `default`.

**Comment by AshesITR** [comment]
SGTM. The tag could be called `tidy_design` for disambiguation.
