### ISSUE TITLE
Usage block interrupts description of condition_message_linter

### ISSUE THREAD

**Issue by jameslamb** [r-lib/lintr#2232]
Looking at https://lintr.r-lib.org/reference/condition_message_linter.html today, I was really confused. It seemed like the docs contained a sentence that was not completed:

> *This linter discourages combining condition functions like [stop()](https://rdrr.io/r/base/stop.html) with string concatenation functions [paste()](https://rdrr.io/r/base/paste.html) and [paste0()](https://rdrr.io/r/base/paste.html). This is because*

<img width="864" alt="Screen Shot 2023-10-06 at 9 58 07 PM" src="https://github.com/r-lib/lintr/assets/7608904/51d4a1b1-06d2-44a9-8fc5-61b64e1fe7a3">

Once I came here to the source code, I realized that that "because" was completed by the bulleted list

https://github.com/r-lib/lintr/blob/b49ee9dac3eddb9285648c9e2b5f15e85659ee3a/R/condition_message_linter.R#L3-L10

I'm not familiar with how `{roxygen2}` handles the case where object documentation just starts in with `#'` without explicitly adding a tag like `@description`... maybe some combination of adding `@description` there plus replacing the use of `-` with an explicit LaTeX `\itemize{}` for that list would help?

Just reporting because I found this confusing. Feel free to close this if that formatting is the intended behavior.

Thanks so much for an awesome library!

**Comment by MichaelChirico** [comment]
This is because... we say so! of course 😂

thanks for reporting, will fix
