### ISSUE TITLE
Extend 'nolint next' to mean the next _expression_?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2241]
Sometimes, we may need a lengthy explanation in a comment for why we're using `nolint next`. I find it's most natural to write such a comment like `# nolint next: undesirable_function_linter. In this case, it's fine to use foo() because reasons. We can revisit if condition changes.`.

It's very easy for such an explanatory comment to run past the `line_length_linter()` limit (especially the default of 80). Therefore it would be nice to support:

```r
# nolint next: undesirable_function_linter. In this case, it's fine
#   to use foo because reasons. We can revisit if condition changes.
foo()
```

The current workaround would be to write the explanation in a preceding comment, which I find less natural:

```r
# In this case, it's fine to use foo because reasons.
#   We can revisit if condition changes.
# nolint next: undesirable_function_linter.
foo()
```

The question is whether this stretches the definition of "next" to a point where it makes less sense / is harder to understand.

**Comment by AshesITR** [comment]
Hmm but in your example, the next expression is the comment starting on the next line, no?

**Comment by MichaelChirico** [comment]
I guess it depends on if comments are "expressions". certainly it's the next entry on the parse tree, but comments are removed from parse(keep.source=FALSE)...

anyway, to be clearer, 'next' would mean next non-comment expression.

**Comment by AshesITR** [comment]
How would we behave if the comment after a nolint next causes a lint (e.g. line length)?
I would still expect

```r
# nolint next: line_length.
# very very very long comment line
```

to work as intended.
So should `# nolint next` cause a nolint up to and including the `@line2` of the next non-comment expression?

**Comment by MichaelChirico** [comment]
Yea, good point. Of course, for `line_length_linter()`, it is usually easy to refactor and wrap your comments... A better example would be something like

```r
# nolint next: line_length.
# http://a-website.with-a-very-long.path.com/blog/2023/10/17/explain-this-code.html
```

Where the comment can't really be split.

And other linters that typically obtain in comments also need consideration, e.g.`todo_linter()` and `commented_code_linter()` off the top of my head.

I would not go to `@line2` of the next expression but `@line1`... other than that the behavior seems OK. But I'm definitely second-guessign.

**Comment by AshesITR** [comment]
Just a hunch, but it might be easier to support `# nolint next N: linter.` instead.

**Comment by MichaelChirico** [comment]
I'm warming to using `# comments...\n# nolint next: linter.` We can consider implementing `# nolint next N` if there's any user interest eventually.
