### ISSUE TITLE
Website: error in example of `lint()`

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/lintr#2243]
The call to `lint()` fails in the ["Examples" section](https://lintr.r-lib.org/dev/reference/lint.html#ref-examples) of `lint()`, both in stable and devel versions of the website:

![image](https://github.com/r-lib/lintr/assets/52219252/1a1d88fc-9c8b-4f8f-be7c-a4a455a22317)

**Comment by IndrajeetPatil** [comment]
Similar to #1887

**Comment by etiennebacher** [comment]
Oups, didn't see this duplicate. I close this issue
