### ISSUE TITLE
FR: add a function `lint_changed_files()` 

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/lintr#2251]
Currently, my workflow when I make a PR is to commit and push the changes, check the results of the `lint-changed-files` workflow (usually fails), and then fix the lints. The main reason I do this is because I don't want to run `lintr` on the whole package locally when I changed only 4-5 files, and I also don't want to manually list the changed files and provide them to `lint()`.

Would it be possible to have something like `lint_changed_files()` that uses the following code to get the list of modified files and applies `lint()` on them? 
```r
system2("git", paste("diff --name-only", "."), stdout = TRUE)
```
This uses `git` directly, but at the same time this function only makes sense when you use version control so I don't think it's a problem. It would also be possible to use the code in `lint-changed-files` but that would add a `gh` dependency.

This is probably related to #2135.

**Comment by etiennebacher** [comment]
> any reason not to use a cache locally?

I just didn't know the existence of the cache, thanks. 

>  is lintr integrated with your IDE?

I use RStudio, so yes I guess

**Comment by MichaelChirico** [comment]
be sure to check the editors vignette as well to get lints inside rstudio as you work:

https://lintr.r-lib.org/articles/editors.html
