### ISSUE TITLE
Custom metadata for top-level '(a <- foo(x))' being used to induce printing

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2257]
Have seen a few hits on `implicit_assignment_linter()` like:

```r
(a <- foo(x))
```

Here, the lint message can mention explicitly using `print()` for readability rather than this shorthand.

We should of course be careful not to mix this case which is similar on the parse tree:

```
AA && (BB <- foo(x))
```

**Comment by AshesITR** [comment]
Agreed. Linting only a top-level parenthesis means the XPath should start with `/` instead of `//`.
