### ISSUE TITLE
New Linter: use symbols instead of quoting functions

### ISSUE THREAD

**Issue by llrs** [r-lib/lintr#2280]
I recently read some discussions about the differences between `do.call("rbind", ...)` and `do.call(rbind, ...)`.  
R-core is [changing some internal code](https://github.com/r-devel/r-svn/commit/786d5a44a338c71d09b8e1ee32ef5fbabb8ef1ec) to use the later.

Similarly, there is [another change](https://github.com/r-devel/r-svn/commit/3cabcd4fd011e95e3f9de405d91c21f2653d4efc) replacing some calls to "[" to "\`[\`" to avoid an internal call to `match.fun()`. 

I couldn't find a linter for this; is this something that could be useful?
This linter might be under[ "Efficiency linters"](https://lintr.r-lib.org/reference/efficiency_linters.html)

**Comment by IndrajeetPatil** [comment]
Related to https://github.com/r-lib/lintr/issues/1444

**Comment by MichaelChirico** [comment]
Closing as dupe of #1444, made sure to note there that `do.call()` is one of the functions to lint. Thanks!
