### ISSUE TITLE
VSCode not using .lintr file

### ISSUE THREAD

**Issue by b-rhodes** [r-lib/lintr#2296]
I'm not 100% sure what I'm doing wrong but I've got a `.lintr` file in `C:/Users/<user>/.lintr` and it's being totally ignored.

In my terminal (outside of vscode) it works fine and I can can use `lintr::lint()` but the terminal within VSCode will ignore the `.lintr` file too.

If I run `options("lintr.linter_file" = "C:/Users/<user>/.lintr")` then after that it starts working within the terminal, but that doesn't change how it displays in the code window (meaning the `.lintr` file is still ignored.

**Comment by AshesITR** [comment]
That may be an editor integration problem.
Note also that Windows `~` expands to `%USERPROFILE%\Documents`, so you might have success by moving your config to `Documents`.
See `normalizePath("~")` to confirm.

**Comment by MichaelChirico** [comment]
cc @renkun-ken as well

**Comment by b-rhodes** [comment]
> See `normalizePath("~")` to confirm.

Thank you for pointing this out, turns out it was inside the onedrive directory for some reason:
`C:\Users\<me>\OneDrive\Documents`.

It might be worth adding `normalizePath("~")` to the documentation?
