### ISSUE TITLE
unnecessary_nesting_linter() can catch else { if () } where the braces could be dropped

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2317]
```r
if (x == 'a') 1 else { if (x == 'b') 2 else 3 }
```

`else {` is not considered by the current logic.

**Comment by AshesITR** [comment]
Maybe instead add a linter that lints `else { if () ... }` if there are no expressions after the `if` expr-block?
Might fit into `brace_linter()`"do not put `{` between `else` and `if` if the `if` branch is the only statement in the `else` block." or something more readable with the same intent...

**Comment by MichaelChirico** [comment]
could also appropriate for unnecessary_nested_if_linter(), or unnecessary_nesting_linter()?

(we might want to merge those two both as unnecessary_nesting_linter?)

**Comment by MichaelChirico** [comment]
@IndrajeetPatil WDYT about subsuming `unnecessary_nested_if_linter()` into `unnecessary_nesting_linter()`?

**Comment by IndrajeetPatil** [comment]
That's a great idea!
