### ISSUE TITLE
Find ways to improve performance of `object_overwrite_linter()`

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2337]
I think we know it's bound to be slow in general since there are so many exports by default (I see 2,591 names to check in R4.1.3).

Still #2328 shows it's faster only than `cyclocomp_linter()` in the current suite.

One concrete idea is to try sorting. Branch prediction intuition tells me if we sort the set of functions to search for, it will be faster. I _assume_ we need to sort in C order, though, which is a bit more subtle & requires some investigation.

**Comment by MichaelChirico** [comment]
Quick experiment:

```r
system.time(replicate(5, lint_package(linters = l)))

# No sorting
   user  system elapsed 
128.161   1.103 129.687 

# sort() in system locale 
   user  system elapsed 
128.227   1.047 129.665 

# force C locale sorting
   user  system elapsed 
127.524   1.068 128.912 
```

So, looks like a _very small_ benefit from sorting _in C locale only_. Not sure it's worth pursuing, unless we want it to be something `xp_text_in_table()` does by default more generally. If so, I'd like it to be controlled by an option since we can imagine cases where `xp_text_in_table()` in put is intentionally ordered to exit early on the likeliest input.

**Comment by MichaelChirico** [comment]
#2341 and #2341 have two small chips at the problem.

Another idea would be to try and ignore S3 generics, or to offer an argument like `name_regex` that filters exports for matching certain patterns e.g. "all letters" which could default to e.g. `^[a-zA-Z0-9]+` i.e. excluding `[._]`.

```r
sum(grepl(paste0("^(", paste(Filter(\(x) make.names(x) == x, .base_s3_generics), collapse = "|"), ")[.]"), pkg_exports$name))
[1] 373sum(grepl(paste0("^(", paste(Filter(\(x) make.names(x) == x, .base_s3_generics), collapse = "|"), ")[.]"), pkg_exports$name))
# [1] 373
```

i.e. 373 (~15%) among defaults look like methods to base S3 generics

**Comment by AshesITR** [comment]
I think the main problem is we compile a giant XPath instead of taking an approach similar to object_name_linter and extracting relevant assigned symbols in the actual code.

**Comment by MichaelChirico** [comment]
maybe this should just be combined with object_name_linter?

**Comment by AshesITR** [comment]
I wouldn't combine them because `object_overwrite_linter()` will yield many annoying lints, because so many "nice" names are used by base already. Or is there a tidyverse styleguide note saying "don't overwrite anything from base and recommended packages"?

**Comment by MichaelChirico** [comment]
> is there a tidyverse styleguide note saying "don't overwrite anything from base and recommended packages"?

there's this (already cited in ?object_overwrite_linter):

https://style.tidyverse.org/syntax.html#object-names

but I read that much like the rule in one_call_pipe linter -- it's really a weak recommendation and not intended (IMO) as a strict rule ("where possible"). so we shouldn't turn it on by default

**Comment by AshesITR** [comment]
Then let's keep them separate. #2344 improves performance drastically as I suspected.

**Comment by AshesITR** [comment]
NB I noticed `NEWS.md` is missing for `object_overwrite_linter()`.

**Comment by AshesITR** [comment]
@MichaelChirico do we want to try harder, or close this issue?

**Comment by MichaelChirico** [comment]
Let's close it, your approach is very good. We can revisit later if needed.
