### ISSUE TITLE
Investigate performance of backport_linter()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2338]
#2328 found `backport_linter()` to be among the slowest in the suite. This is surprising to me, it seems like a relatively simple linter.

**Comment by AshesITR** [comment]
#2348 takes another chip.
Not sure there is much room for improvement after that.

**Comment by MichaelChirico** [comment]
I suspect we can improve by honing the XPath:

```
 names_xpath <- "//SYMBOL | //SYMBOL_FUNCTION_CALL"
```

To only look for `text() %in% possible_backport_issues`, I toyed around with that a little but didn't finish up b/c I got tripped up with the data structure issue you've solved in #2348.

Now that that's fixed I'll have another go.

**Comment by AshesITR** [comment]
SGTM. I'll clean up #2348.
