### ISSUE TITLE
Add `linter_level` to `Linter()` metadata.

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#2351]
Here's what cost > 1s in `lint()` during `lint_package()` currently:
![image](https://github.com/r-lib/lintr/assets/2363178/1ea0b42b-d1cb-4fc9-97c1-a007eaf9a537)

We can see 30% of the time is spent in `xml_find_all()`.
What surprised me was `is_lint_level()` taking a whole 8s. That may be worth converting to an attribute of `Linter()`?

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/issues/2350#issuecomment-1825195389_

**Comment by AshesITR** [comment]
~10% of the time `lint_package()` took (80s) is spent in `is_lint_level()`.
We could avoid this by adding an attribute to `Linter()` that specifies `lint_level`.

For maximum backward compatibility, I suggest it to default to `NA_character_` keeping the current behavior.
If it is set to `"file"` or `"expression"`, only those `source_expressions` should be passed into the linter.
This means we can drop the check for all our linters and delegate it to `lint()` checking linter attributes.

**Comment by MichaelChirico** [comment]
I've actually had in mind something along these lines, namely, that most linters could be toggled very easily between `file`- and `expression`-level operation, with the difference _maybe_ being a slight difference in the XPath (but in most cases the same XPath works for both cases).

It would be nice to have an easy API through `lint()` to say "I don't care about expression-level cacheing, just run file-level lints".

**Comment by AshesITR** [comment]
Working on this atm (diff will be large because it needs to touch all linters for the performance benefits)
