### ISSUE TITLE
Do we want `# nolint prev`?

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#2353]
I felt it looked less cluttered here because all that exceeds the line are nolint statements.
I worry that a `# nolint next` would mess up roxygen here. Maybe time for a `# nolint prev`? 😁 

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2352#discussion_r1404591876_

It would help with keeping function declarations and roxygen documentation neat with the same advantages as `# nolint next`.

**Comment by MichaelChirico** [comment]
With that in mind, I will close here to avoid some feature creep, we can revisit if there's a more compelling use case.
