### ISSUE TITLE
Confusing (misleading?) lint message from `nzchar_linter()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#2383]
The current message makes it seem like the `nzchar()` is a drop-in replacement for  `nchar(x) == 0`; at least that's my read of it.

``` r
library(lintr)
lint(
  text = 'if (nchar(x) == 0L) print("x is empty")',
  linters = nzchar_linter()
)
#> <text>:1:5: warning: [nzchar_linter] Instead of comparing nchar(x) to 0, use nzchar(). Whenever missing data is possible, please take care to use nzchar(., keepNA = TRUE); nzchar(NA) is TRUE by default.
#> if (nchar(x) == 0L) print("x is empty")
#>     ^~~~~~~~~~~~~~
```

But, instead, the `nzchar()` result needs to be negated to get the equivalent output:

```r
x <- ""
identical(
  nchar(x) == 0L,
  !nzchar(x)
)
#> [1] TRUE
```

<sup>Created on 2023-12-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Can we refine the lint message to reflect this?

**Comment by MichaelChirico** [comment]
I was careful to phrase it as "compare to 0" to avoid this issue, but agree it's even better to customize the message.
