### ISSUE TITLE
consider/clarify "unnecessary" part of "unnecessary_lambda_linter"

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/lintr#2421]
Just want to flag pre 3.1.1 release that there is a "small" benefit to using lambdas (particularly in a more interactive/scripting setting) in terms of the error message displayed

``` r
testy <- function(x) lapply(x, sum)
testy_lambda <- function(x) lapply(x, \(x) sum(x))
testy("bob")
#> Error in FUN(X[[i]], ...): invalid 'type' (character) of argument
testy_lambda("bob")
#> Error in sum(x): invalid 'type' (character) of argument
```

Only small and still slightly unhelpful due to `lapply` not being referenced but I wonder if it at least warrants discussion in the "details" section of the docs.

**Comment by IndrajeetPatil** [comment]
See https://github.com/r-lib/lintr/issues/1871 where there is related discussion taking place.

**Comment by MichaelChirico** [comment]
Thanks for filing! Agree with Indrajeet that #1871 is a good place to address this.
