### ISSUE TITLE
Different default lints when running on a package

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/lintr#243]
Because some lints only make sense in packages.

**Comment by MichaelChirico** [comment]
@gaborcsardi PTAL at https://github.com/r-lib/lintr/blob/master/inst/lintr/linters.csv -- `tags` + `linters_with_tags()` is the way to do this. `package_development` gets close to what you want but probably not quite. Happy to take a PR extending the tags or other suggestions about how to improve UX for this.
