### ISSUE TITLE
Do not evaluate code in object_usage_linter

### ISSUE THREAD

**Issue by gdkrmr** [r-lib/lintr#248]
linting a file from the repl with `lint()` containing only the line `plot(function(x) x^2, from = -1, to = 1)` opens a plotting window.

I am using lintr v1.0.0 from CRAN

**Comment by jimhester** [comment]
The `object_useage_linter()` evaluates top level code during the linting process, so this is expected. 

I have future plans to remove this dependency however.

**Comment by MichaelChirico** [comment]
IINM this is subsumed by #912
