### ISSUE TITLE
expect_lint_free assumes package is in the working directory by default

### ISSUE THREAD

**Issue by jimhester** [r-lib/lintr#251]
This causes problems when running reverse dependencies with `devtools::revdep_check()`, as the working directory is _not_ the package directory in that case.

`expect_lint_free()` should instead default to check the package being tested, which is a little trickier to implement.

**Comment by MichaelChirico** [comment]
This hasn't gotten any traction in almost 7 years, and there's no ready repro here, so closing until this is requested.
