### ISSUE TITLE
Is it possible to exclude individual linters on directory (not file) level?

### ISSUE THREAD

**Issue by pawelru** [r-lib/lintr#2517]
I'm looking for something like this:
```
exclusions: list(
    "vignettes" = list(
      object_name_linter = Inf
    )
  )
```

But this actually disables all the linters - not only `object_name_linter`. I can put there `foo` and the result will be the same - disable all linters (or maybe: all files in that dir?)

If this is not possible - please consider this as a feature request.

**Comment by MichaelChirico** [comment]
See #2172 and #1554, if you think those would cover your use case we can close this.

**Comment by pawelru** [comment]
Thanks. It's definitely related. Upvoting these issues and closing this as a duplicate.
