### ISSUE TITLE
docs: return() is not undesirable

### ISSUE THREAD

**Issue by maelle** [r-lib/lintr#2532]
In https://lintr.r-lib.org/reference/undesirable_function_linter.html

> Report the use of undesirable functions (e.g. [base::return()](https://rdrr.io/r/base/function.html), [base::options()](https://rdrr.io/r/base/options.html), or [base::sapply()](https://rdrr.io/r/base/lapply.html)) and suggest an alternative.

But return() is not an undesirable function?

**Comment by MichaelChirico** [comment]
Nice catch! I think this is vestigial, at some point `return` was considered undesirable:

https://github.com/r-lib/lintr/blob/91b53acf69166c9054b054b2602038e48e42b066/R/zzz.R#L132

**Comment by MichaelChirico** [comment]
Yes, this was #1146 and #1149
