### ISSUE TITLE
Is there any way to skip the checking of glue syntax in name injection?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/lintr#2544]
https://dplyr.tidyverse.org/articles/programming.html?q=glue#name-injection

**Comment by MichaelChirico** [comment]
Could you give a more specific example of code that lints now that you'd like not to lint?

Do note that you can run `object_usage_linter(interpret_glue=FALSE)` already.

**Comment by ramiromagno** [comment]
I am using lintr in a github action.

This code:

```R
dplyr::mutate("{tgt_var}" := tgt_val)
```

gives this:

```
[object_name_linter] Variable and function name style should match snake_case or symbols.
```

**Comment by MichaelChirico** [comment]
oh, got it, this is #1926
