### ISSUE TITLE
Bump minimum R version to >=4.0

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2569]
Tidyversion R version support say we are now up to R>=4.0.0:

https://www.tidyverse.org/blog/2019/04/r-version-support/

There are of course some nice features in 4.0.0 we can start using, so it will be nice to take advantage of that.

OTOH, the current CRAN version only depends on R 3.5.0, so I would not make 2 version jumps in the same release. Let's release 3.2.0 with R>=3.6.0, then bump to 4.0.0 afterwards.

**Comment by AshesITR** [comment]
Why not bump to 4.0.0 immediately?

**Comment by MichaelChirico** [comment]
I think some caution is warranted.

 1. No tidyverse packages have actually updated to R>=4.0.0 yet
 2. We don't have any releases with R>=3.6.0 requirement yet

I don't see any particular reason to rush.

**Comment by AshesITR** [comment]
I would only bump the R version dependency if an old version actually breaks, so if we don't use any 3.6 only features, I wouldn't lock 3.5 out of lintr updates.

**Comment by IndrajeetPatil** [comment]
Strongly disagree. I don't want us to make empty promises to users. 

Neither CRAN nor our CI builds or tests the package on `R < 3.6`. Unless we add this as a manual step to carry out before submitting the package to CRAN, there is no point in continuing to _support_ older versions. 

Without testing anything, we might as well support `R > 2.0` to not lock anyone out. And, yes, I am being hyperbolic just to emphasize my argument 😉

**Comment by IndrajeetPatil** [comment]
Because `{evaluate}` now needs R >= 4.0: https://cran.rstudio.com/web/packages/evaluate/index.html, so does its reverse dependency `{knitr}`, which is runtime dependency for `{lintr}`. 

So, whether we bump it or not in the `DESCRIPTION`, we effectively depend on `R >= 4.0`.
