### ISSUE TITLE
`min_r_version_linter()` to detect invalid or missing minimum R version in R package

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#2576]
The problem is explained quite well through this example: https://github.com/rvlenth/emmeans/issues/489

With the precedent of the cyclocomp linter, we can now introduce linters that use a suggested dependency, and I think this would come in handy here. In particular, I think the [dependency solver](https://r-lib.github.io/pkgdepends/reference/index.html#package-dependencies) in `{pkgdepends}` can be quite helpful to figure out the correct minimum needed R version. 

Of course, this is going to detect the minimum required R version only by looking at the dependency graph. Figuring that out by checking if any newer R functions are used would be a more challenging task, and I don't consider that to be in the scope of this issue.

WDYT?

**Comment by MichaelChirico** [comment]
Funny, I just filed https://github.com/r-lib/rcmdcheck/issues/220 yesterday.

I'm not seeing how this works as an R linter though, isn't this a DESCRIPTION linter? But then it's out of scope: #889

**Comment by IndrajeetPatil** [comment]
> then it's out of scope

Can we please relitigate this? 

We do support a class of linters that are designed for package development and, given that it's the DESCRIPTION file that turns a folder into package, I think linting its contents could also fall under the purview of _lintr_.

**Comment by AshesITR** [comment]
This really seems like more trouble than it's worth to me.
Here are some thoughts on the matter:

If we were to support linting DESCRIPTION files, this would need to be supported in `lint()` so we need to make a smart (= complex?) way to determine how to proceed with linting the requested file. Alternatively, we could provide completely separate entry points, like `lint_description()`.
Then, how to we handle config management for these linters? And how do we do name description linters to separate them from R code linters?
Or, if we don't, how do we setup linter metadata to deal with different languages, likely requiring completely separate parsing logic?

**Comment by IndrajeetPatil** [comment]
Hmm, yeah, I see what you mean.

We probably need to outsource this either to another package (e.g. [`{goodpractice}`](https://github.com/ropensci-review-tools/goodpractice/blob/c8a4671160d88ca9fcac995ba2931fcec9b699b6/R/chk_description.R)), or, if we have enough issues, we could consider creating a new extension package of `{lintr}` that deals only with lints related to the `DESCRIPTION` file (and other package-related metadata).

**Comment by IndrajeetPatil** [comment]
Should I create an issue to scope out `{lintr.meta}`, which we can keep updating as we think of new features?

This would actually be a good candidate for [GitHub Discussions](https://docs.github.com/en/discussions/quickstart). 
@MichaelChirico Do you have the necessary privileges for this repo to turn on _Discussions_? Just an idea; I am also fine with using issue for this.

**Comment by IndrajeetPatil** [comment]
Borrowing from Hadley:

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

deps <- pak::pkg_deps("lintr", upgrade = TRUE)
#> ℹ Loading metadata database
#> ✔ Loading metadata database ... done
 
deps$deps |> 
  set_names(deps$package) |> 
  map(\(df) df |> filter(ref == "R") |> select(version)) |> 
  list_rbind(names_to = "package") |> 
  arrange(desc(package_version(version))) |>
  head(1L)
#> # A data frame: 1 × 2
#>   package  version
#> * <chr>    <chr>  
#> 1 evaluate 4.0.0
```

<sup>Created on 2024-06-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
