### ISSUE TITLE
New function expect_no_lint() akin to expect_no_warning() etc

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#2580]
Is there by the way an `expect_no_lint` function? I would have expected a wrapper for `expect_lint(content, NULL, ...)`.

_Originally posted by @F-Noelle in https://github.com/r-lib/lintr/pull/2574#discussion_r1600474890_

**Comment by F-Noelle** [comment]
This issue can be considered closed. Especially since #2585 can be considered a follow up issue.
