### ISSUE TITLE
Linting is too agressive

### ISSUE THREAD

**Issue by Jacinto27** [r-lib/lintr#2592]
Too many miniscule and almost meaningless errors are raised by  default on the languageserve package, and consecuently, the VS Code extension and implementation of the lintr package. Perhaps some communication between lintr and languageserver to create a better default? 

Info:
 
[ vs-codeR: Less aggressive linting #1400](https://github.com/REditorSupport/vscode-R/issues/1400) 

[lintr documentation regarding the languageserver defaults](https://lintr.r-lib.org/articles/editors.html#visual-studio-code) 

Don't know if issue has been raised here already. Checked closed issues and found nothing, did not check open issues.

**Comment by MichaelChirico** [comment]
{lintr} will not change its defaults; enforcing the tidyverse guide is a core development principle of the package.

If there is any FR for improving how to set lint configuration, please elaborate. Or if this is a documentation issue, that is also something we can help with. PRs especially welcome.

Barring that, it looks like a VScode issue -- as noted they already ship a non-default `line_length_linter()`, so they should be willing to ship non-defaults for other linters too. It looks like that default config is here:

https://github.com/REditorSupport/vscode-R/blob/b196c7d8257a04509de68a3bfe7acf9c1f2fba85/R/.lintr#L2

**Comment by Jacinto27** [comment]
In other words, there is nothing peculiar to this extension. This is the default configuration for the lintr package

_Originally posted by @eitsupi in https://github.com/REditorSupport/vscode-R/issues/1400#issuecomment-1867864350_
            
> Barring that, it looks like a VScode issue -- as noted they already ship a non-default `line_length_linter()`, so they should be willing to ship non-defaults for other linters too.

??

Despite this, given that vscode-R is the final user, it should be their responsability to wrap it's dependencies, especially considering that "the tidyverse guide as a default is a core development principle of the package", and avoid people fidgetting with the lintr file. Will reference these comments on the vscode-R repo.
