### ISSUE TITLE
Cleaner output in the examples on the website?

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/lintr#2632]
The examples on the website have an annoying prefix before them:

![image](https://github.com/user-attachments/assets/7525512e-ab66-47b1-bedb-c4723a68cd8a)

I might be missing something but it seems to me that this prefix is here to correctly mark lints in Github actions output: https://github.com/r-lib/lintr/blob/main/R/actions.R

I guess the issue is that the `pkgdown` workflow runs on Github actions so this printing method is enabled. However, I don't think it's useful to show this on the website. Maybe you could tweak `in_github_actions()` to be `FALSE` when `IN_PKGDOWN` is `TRUE`?

**Comment by IndrajeetPatil** [comment]
Good idea. See https://github.com/r-lib/lintr/pull/2633 :)
