### ISSUE TITLE
Default tab length to 4 spaces - excessive and unhelpful linting

### ISSUE THREAD

**Issue by PD-LUHC** [r-lib/lintr#2652]
Using VS Code set to default tab size of 4 I get scripts peppered with tab size linting, insisting that tab size should be 2. I know that R studio defaults to 2 spaces but this is contradictory to the [R coding standards recommendations on indents](https://cran.r-project.org/doc/manuals/R-ints.html#R-coding-standards) and just about every other language out there.

Would it make sense for the linting of tab sizes to be set to the standard or even turned off by default? Following the standard makes sense as it's, the standard. Turning it off also makes sense as most of the time tab sizes are set at an IDE level and people generally don't need to make corrections after it is set - the sheer volume of tab linting in some documents really aren't merited by the severity of the problem, to the point where the volume of lints becomes a problem in itself.

Hope that makes sense.

**Comment by AshesITR** [comment]
We follow the tidyverse styleguide by default, which mandates two spaces: https://style.tidyverse.org/syntax.html#indenting

You can customize the indentation using your own lintr condfig file, though.
