### ISSUE TITLE
Add more explanation to the `assignment_linter()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#2694]
I wanted to refer to `{lintr}` docs in https://github.com/tidyverse/style/issues/237, but realized that it doesn't give any explanation either.

It would be good to include some documentation explaining why it might be preferable to use `<-` over `=`.

**Comment by AshesITR** [comment]
IMO the most important thing is consistency. If you commit to always use `=`, your code will turn out equally readable. It just happens to be that the style guide choses to prefer `<-` since it's more widespread among R users.

**Comment by MichaelChirico** [comment]
The style guide is where such explanation belongs IMO, and linked from our docs. Don't think there's anything we should do.
