### ISSUE TITLE
Lint for test/testhat vs R/ naming consistency

### ISSUE THREAD

**Issue by hadley** [r-lib/lintr#296]
i.e. every `test-` file in `tests/testthat/` should have a corresponding file in `.R`

**Comment by cwhoffmannch** [comment]
I am badly missing any (working)mexamples in the lintr package

**Comment by MichaelChirico** [comment]
Since this doesn't really have anything to do with R code _per se_, I'm not sure this is in scope for `lintr`. I think it's very similar to #889.

**Comment by AshesITR** [comment]
NB while I agree think it is out of scope for lintr, that's something I stumbled upon in lintrs code base before.
