### ISSUE TITLE
Feature to only show warning/error lints

### ISSUE THREAD

**Issue by q23qweliuhan** [r-lib/lintr#309]
Hi Jim,

Thanks for the great work.
Since we have a legacy code base, we cannot fix all the lints at once.
Triggered by this, I'm wondering if it will be a useful feature to allow the user to optionally enable a certain type of lintrs. For example, I would like to check all the warning and errors, but not the style ones.
Here I don't mean the individual lintrs, I know that can be done with the configuration file.

Best regards,
Hang

**Comment by jimhester** [comment]
The returned lints are basically just a list of `lintr::Lint()` objects, so you can filter them like you would any other list. e.g.

``` r
lints <- lintr::lint(system.file("example/bad.R", package = "lintr"))
purrr::keep(lints, ~ .$type %in% c("error", "warning"))
#> .../3.4/library/lintr/example/bad.R:3:3: warning: local variable 'one.plus.one' assigned but may not be used
#>   one.plus.one <- oen + 1
#>   ^~~~~~~~~~~~
#> .../3.4/library/lintr/example/bad.R:3:19: warning: no visible binding for global variable 'oen', Did you mean 'one'?
#>   one.plus.one <- oen + 1
#>                   ^~~
#> .../3.4/library/lintr/example/bad.R:4:11: warning: local variable 'newVar' assigned but may not be used
#>   four <- newVar <- matrix(1:10,nrow = 2)
#>           ^~~~~~
#> .../3.4/library/lintr/example/bad.R:7:3: warning: local variable 'three' assigned but may not be used
#>   three <- two+ 1
#>   ^~~~~
#> .../3.4/library/lintr/example/bad.R:7:12: warning: no visible binding for global variable 'two', Did you mean 'txt'?
#>   three <- two+ 1
#>            ^~~
#> .../3.4/library/lintr/example/bad.R:10:1: error: unexpected end of input
#> {
#> ^
```

Created on 2018-03-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by q23qweliuhan** [comment]
Thanks Jim for the quick response!
The only issue with this approach is that I cannot do post processing if I want to use expect_lint_free() with CI.
But I'll just use lint_package() and do a manual detection if any lint exists.

**Comment by jimhester** [comment]
That is true, we could potentially add a `types` argument to `lint_package()` that would include only those types in the output in that case.

**Comment by q23qweliuhan** [comment]
Indeed, that would be a nice feature!

**Comment by AshesITR** [comment]
I don't think `lint()` should be getting this argument. If you don't want a `style` lint, you can disable the corresponding linters using the `linters` argument or one of the ways to configure it. The set of linters issuing warnings / errors is quite small 

What sounds useful though might be to extend `expect_lint_free` to allow ignoring `"style"` lints (or even `"warning"`, but not so sure if that's useful as `"error"` lints pretty much only come up on parse errors).

Apart from parse errors, these linters produce warnings:

backport_linter (non-default)
equals_na_linter
extraction_operator_linter (non-default)
missing_argument_linter (non-default)
missing_package_linter (non-default)
namespace_linter (non-default)
object_usage_linter
path_linters (non-default)
seq_linter 
sprintf_linter (non-default)
undesirable_function_linter (non-default)
undesirable_operator_linter (non-default)
unneeded_concatenation_linter (non-default)

**Comment by MichaelChirico** [comment]
@AshesITR WDYT about adding style/warning as tags? then this issue could be solved with `linters_with_tags("warning")`?

**Comment by AshesITR** [comment]
Not sure it's worth it. The lint type is somewhat arbitrary and we can't guarantee that all lints from linters with this tag will have this type.

**Comment by MichaelChirico** [comment]
In that case I think it's OK to close. If there would be sufficient demand that would be the way forward. I'm also a bit wary & think just disabling unwanted linters is best.
