### ISSUE TITLE
post github comments as inline code review

### ISSUE THREAD

**Issue by mattyb** [r-lib/lintr#364]
The github commenting is a neat feature of lintr. Since the comments aren't tied to commits however, it can be difficult to tell when if a lint comment is still relevant. It would be more powerful if the comments were posted as code review comments with a position value, so they would show up inline with the code and be marked as outdated if the code changes.
https://developer.github.com/v3/pulls/comments/#create-a-comment

**Comment by jimhester** [comment]
I agree! The code review API did not exist when this was implemented in lintr, which is why this has not the way it currently works.

**Comment by MichaelChirico** [comment]
Check the discussion on #1558. We think the current setup is even more convenient (lints are posted as annotations in the `Files` page of a PR). See #854 as well for further reference.
