### ISSUE TITLE
feature request: allow long URLs in roxygen comment blocks

### ISSUE THREAD

**Issue by jackwasey** [r-lib/lintr#379]
It would be nice to (?optionally) ignore line length in roxygen blocks for URLs. I frequently have long URLs to academic references, stackoverflow, etc., and can't use #nolint because it would show up in the documentation. I also don't want to hard-code line numbers to ignore.

Could an exception be made in the line_length_linter just for URLs?

I'm not aware of any way of breaking up the URLs in a roxygen block such that they are reconstructed in the documentation.

**Comment by russHyde** [comment]
Interesting. I didn't know the current version linted the roxygen docs. An alternative might be to modify the `line_length_linter` to specify whether it should be active on the first- or the last- letter in the final word on a given line. 

I also find that I go over my line width when I use the following format in my function definitions:

```
some_pretty_specific_function <- function(my_argument,
                                                                    my_default_argument = "OMG I'm over|||board"
                                                                    )
```

**Comment by jimhester** [comment]
You can use `#no lint start`, `#no lint end` around the roxygen block to turn off linting within it.

**Comment by davidorme** [comment]
Just to say that the docs (https://github.com/jimhester/lintr#project-configuration) show the default exclude patterns are (now?) `# nolint start` and `# nolint end`.

**Comment by IndrajeetPatil** [comment]
As mentioned in the comments, using the nolint directives around the roxygen block is the way to go here.

**Comment by rempsyc** [comment]
> Just to say that the docs (https://github.com/jimhester/lintr#project-configuration) show the default exclude patterns are (now?) # nolint start and # nolint end.

For the clarity of future readers coming here, I just want to specify that this will _only_ work if specifically written now as  `# nolint start` and `# nolint end` **with a space after the `#` and no space between `no` and `lint`**. I was looking at previous comments and didn't noticed this nuance and was really confused for a while why it wasn't working when using `#no lint start` and `# no lint start`.

**Comment by IndrajeetPatil** [comment]
FWIW, running `{styler}`, should make remembering to add space unnecessary:

``` r
styler::style_text('x <- "a" #nolint: object_usage_linter.')
#> x <- "a" # nolint: object_usage_linter.
```

<sup>Created on 2024-04-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
Also, the ignore directives are customizable: you could change the following settings to `#no lint start` and `#no lint end`, resp., if that's your preferred way:

``` r
library(lintr)

default_settings$exclude_start
#> #[[:space:]]*nolint start
default_settings$exclude_end
#> #[[:space:]]*nolint end
```

<sup>Created on 2024-04-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
