### ISSUE TITLE
Behavior of lintr before/after calling library

### ISSUE THREAD

**Issue by tvatter** [r-lib/lintr#415]
Apologies, I just wanted to make sure that #382 wouldn't be forgotten, since you seem to be almost ready for a release, but the issue has been closed without solution (I think)... Or is there something that I'm completely missing? In this case, sorry to waste your time!

**Comment by jimhester** [comment]
It is not going to be addressed, sorry.

**Comment by tvatter** [comment]
Even the `Rscript -e 'lintr::lint("test.R")'` vs `Rscript -e 'library(purrr);lintr::lint("test.R")'` behavior?

**Comment by tvatter** [comment]
I mean, I understand that vim isn't a priority, but issues related to this behavior might happen in other editors no?

**Comment by MichaelChirico** [comment]
Not enough context in this issue; please open a new issue with a reprex if this is still a concern
