### ISSUE TITLE
Space between "return" and a left parenthesis

### ISSUE THREAD

**Issue by flaviobello** [r-lib/lintr#435]
Linting the following code:
```
square <- function(x) {
  return (x * x)
}
```
results in:
```
R/test.R:2:10: style: Remove spaces before the left parenthesis in a function call.
  return (x * x)
         ^
```
However, "return" is not a function call. To be consistent with "for" and "if", a space should be allowed (maybe enforced?) before the parenthesis. This should be fixed in `function_left_parentheses`. Also, for consistency with "for" and "if", there should be a style warning if there is no space between return and a left parenthesis (maybe in `spaces_left_parentheses_linter`).

**Comment by russHyde** [comment]
Could you explain why you don't consider `return` to be a function, please.

**Comment by flaviobello** [comment]
`return` is a language element, as are `break`, `for`, `function`, `if`, `next`, `repeat` and `while`. 
(see https://cran.r-project.org/doc/manuals/r-release/R-ints.html#g_t_002eInternal-vs-_002ePrimitive)
It is used to define the value to be returned by a function and interrupt execution of further statements, but it is not itself a regular function. Like 'if' and 'for', it controls the flow of program execution, something that regular functions do not.

**Comment by klmr** [comment]
> However, "return" is not a function call. 

No, that’s incorrect. In R, `return` *is* a pure function call, unlike language constructs such as `for` and `function`.

**Comment by MichaelChirico** [comment]
The space before function is also a violation of the style guide:

https://style.tidyverse.org/syntax.html#parentheses

I think the rules described in this issue are enforced in lintr as they're described in the guide. As such I think it's up to custom linters to define different behavior. Please re-open if I am in error.

**Comment by klmr** [comment]
@MichaelChirico Yes, I see that my previous comment describes (what I consider) an inconsistency *in the style guide* (since it prescribes a space after `if`, `for` and `while` but not `function`, despite all three being syntactic deviations from pure function call syntax). — But since the linter rules are supposed to enforce the style guide they are obviously correct.
