### ISSUE TITLE
lintr-bot comments not updating in PR

### ISSUE THREAD

**Issue by goldingn** [r-lib/lintr#444]
lintr bot gave me some useful linting comments in a PR:
https://github.com/greta-dev/greta/pull/327#commitcomment-36719618

then I pushed a change fixing the issues:
https://github.com/greta-dev/greta/pull/327/commits/85e9a0798da53b28174a392e0c88ed865223903e

and lintr bot commented again, but with the original (now incorrect) comments again:
https://github.com/greta-dev/greta/pull/327#issuecomment-572368115

This is obviously only a minor thing, since the local lintr run tells me it's all good. Just thought I'd flag it in case there is an easy fix.

**Comment by MichaelChirico** [comment]
Is this still an issue? We haven't noticed it in our workflow here. If so, check that your workflow config matches ours. If not, please re-open.
