### ISSUE TITLE
Improve configuration safety

### ISSUE THREAD

**Issue by paulponcet** [r-lib/lintr#446]
Currently the `.lintr` configuration file is read with `read.dcf()`, after which an `eval(parse(text = ..))` command is applied on each field of the result. This use of `eval(parse(text = ..))` seems to me not safe enough, in case I use a `.lintr` provided by someone else. Could this be avoided?

**Comment by russHyde** [comment]
I think you could just use `parse_settings = FALSE` if you don't want to use the .lintr someone else has written
