### ISSUE TITLE
lint_dir must allow recursive parameter 

### ISSUE THREAD

**Issue by Fernal73** [r-lib/lintr#448]
https://www.rdocumentation.org/packages/styler/versions/1.2.0/topics/style_dir

lint_dir must provide a parameter recursive that allows users to specify whether or not all sub-directories are to be processed as well.

**Comment by Fernal73** [comment]
https://github.com/Fernal73/LearnR/blob/development/lintall.R

https://github.com/Fernal73/LearnR/blob/development/lint.R

My use-cases.

**Comment by russHyde** [comment]
Could you explain your use-cases in a bit of detail here please.

Does the `exclusions` parameter provide enough flexibility for your needs?

If this were implemented, should it behave like `recursive` in `base::dir` (use all subdirs) or `recurse` in `fs::dir_ls` (use all subdirs when TRUE, use subdirs to a given depth when numeric)

**Comment by Fernal73** [comment]
> If this were implemented, should it behave like `recursive` in `base::dir` (use all subdirs) or `recurse` in `fs::dir_ls` (use all subdirs when TRUE, use subdirs to a given depth when numeric)


The latter provides added flexibility.

**Comment by Fernal73** [comment]
> Does the `exclusions` parameter provide enough flexibility for your needs?
> 
I've never had to use the 'exclusions' parameter. However, I'm never comfortable specifying line numbers unless there's a way of regenerating the exclusion values without having to manually update them.

**Comment by russHyde** [comment]
You don't have to specify line numbers at all. Just adding the filenames should be sufficient

**Comment by Fernal73** [comment]
That would omit the contents of a file.
If that's what you want.

**Comment by AshesITR** [comment]
The default behavior of `lint_dir()` is to recursively search all files.
So if I understand correctly, you want `lint_dir()` to optionally only lint top-level files?
If so, I think vectorizing `lint()` would be a more intuitive way to do this (so you run `list.files(...)` yourself)

**Comment by MichaelChirico** [comment]
No update for a while, and I'm not totally clear the exact ask here.

Please open a new issue to start the thread from scratch relative to the current state of {lintr} (which has changed a fair amount since this was posted)
