### ISSUE TITLE
Search for non-namespaced functions

### ISSUE THREAD

**Issue by johanneswaage** [r-lib/lintr#453]
In our organisation, and possibly others, all R function calls should be explicitly namespaced for a number of reasons, including legibility and self-documentation, as well as avoiding namespace collisions. 

Could lintr be setup to detect violations of this?

Thanks

**Comment by russHyde** [comment]
Ref #459

**Comment by wkdavis** [comment]
I like this idea. I think you could build on the work of @dreamRs in https://github.com/dreamRs/prefixer.

**Comment by MichaelChirico** [comment]
I believe this is a dup of #459. Please re-open if that's mistaken.
