### ISSUE TITLE
where to get the name of linter in the XML output.

### ISSUE THREAD

**Issue by rahulrachh** [r-lib/lintr#478]
I am using the XML output and would like lintr to print the linter that is being used in displaying an error. Is there a way for XML output to print the ouput once lintr has been installed.

**Comment by MichaelChirico** [comment]
@rahulrachh could you be more specific about your workflow? How are you using `lintr` and what is producing the output that you'd like to improve?

**Comment by MichaelChirico** [comment]
Closing for now -- feel free to re-open if this is still an issue for you and you're able to provide more detail. Thanks!
