### ISSUE TITLE
Skip eval=FALSE chunks?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#581]
I want to use `undesirable_function_operator` to block `install.packages` on some files (where package installation should be handled by a build tool rather than in the script itself), however, it is common for Rmd scripts to include instructions on setting up the environment to reproduce the output that includes `install.packages` in an `eval=FALSE` cell.

I would like to skip linting in such cases -- what's the best way to go about this? An option to skip `eval=FALSE` Rmd cells in `lintr::lint` and `lintr::get_soure_expressions`?

Example:

    writeLines('
    ```{r install, eval = FALSE}
    install.packages("lintr")
    ```
    ', tmp <- tempfile(fileext = ".Rmd"))
    lintr::lint(tmp, lintr::undesirable_function_linter(c(install.packages= "")))

**Comment by AshesITR** [comment]
What would we do about `knitr::opts_chunk$set(eval = FALSE)`?

I think your usecase might better be served by replacing the eval = FALSE chunks by regular souce code chunks with r syntax highlighting using ```` ```r ````.

**Comment by MichaelChirico** [comment]
@AshesITR I think you're right we won't be able to get a complete static solution. But checking explicit chunk options would still be an improvement.

**Comment by russHyde** [comment]
Ran into a similar problem while writing a blogpost that mingles R<4.1 code/env with R-4.1 code:

````
```{r eval = FALSE}
# R 4.1.0 code (but using in an R-4.0.5 environment)
rnorm(100) |>
  density() |>
  plot()
```
````

"Error: unexpected '>'"

**Comment by AshesITR** [comment]
The "malformed file" error should be fixed now, so closing this as using

    ```r
    rnorm(100) |>
      density() |>
      plot()
    ```

Should be the (preferable) way to achieve syntax highlighting without evaluation.

**Comment by MichaelChirico** [comment]
I'm not sure this is fully solved ... but please open a new issue if there's still need for improvement here
