### ISSUE TITLE
Custom linters vignette feels dated and/or incomplete

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#610]
The "Creating new linters" vignette:

https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html

Feels off. Two major shortcomings:

 - It doesn't mention anything about cacheing lints
 - It doesn't mention anything about parsing with the XML tree

I think it would make sense to update the vignette to show how to make a lint cache-friendly (distinguishing between the `full_parsed_content` and expression-level input), as well as to give some insights about how to get going making XPath-based logic for linting.

**Comment by patelaryan7751** [comment]
hello @russHyde can i work on this?

**Comment by MichaelChirico** [comment]
I don't think anyone has any progress yet -- go ahead!!

**Comment by russHyde** [comment]
Welcome on board @patelaryan7751 .

**Comment by patelaryan7751** [comment]
@russHyde @MichaelChirico can you please provide the content which i would be updating there .

**Comment by russHyde** [comment]
I don't have content written. Happy to discuss examples. Have you written a custom linter?

**Comment by patelaryan7751** [comment]
@russHyde Yes  i need some examples. No i have not written any custom linter.

**Comment by russHyde** [comment]
No problem. Would you like to focus on #691 for now @patelaryan7751 . I'll change this issues tag from good-first-issue to help-wanted since it requires some understanding of how to build linters

**Comment by patelaryan7751** [comment]
@russHyde okay!
