### ISSUE TITLE
Create a pkgdown website for `lintr`

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#691]
Do we want a pkgdown website?
We could use github pages to host it.

**Comment by russHyde** [comment]
Crossref: #473

**Comment by russHyde** [comment]
It would be nice to have several vignettes before we do this (otherwise the website would just be a duplication of the help pages):
- a lintr quickstart (covering local use);
- how to use lintr in various IDEs;
- how to use lintr in CI;
- how to configure lintr;
- how to write a linter

A lot of this stuff is already written (in the README and current vignette) but is pretty terse. So it might be useful to get someone from outside our circle to check over any new documentation.

**Comment by patelaryan7751** [comment]
hello @russHyde can i work on this?

**Comment by patelaryan7751** [comment]
@russHyde can you give more info on this  ?

**Comment by russHyde** [comment]
Have you used pkgdown before?

**Comment by patelaryan7751** [comment]
> Have you used pkgdown before?

No! but i can learn how to use it.

**Comment by patelaryan7751** [comment]
> There's details of how to build a site with pkgdown here: https://pkgdown.r-lib.org. We might need Jim to set the 'github pages' links. Once an initial site is working we can discuss how to ensure the site is kept is sync with the source code and any additional vignettes/tutorials that could be written.

Okay , i would be using pkgdown to build the website and after interacting with Jim i would try to complete the whole website.

**Comment by russHyde** [comment]
Do you have any R packages on github? It might make sense to try using pkgdown on one of your own packages first, to find out how it works.

If it's of interest, these are the changes that running `pkgdown::build_site()` added to one of my packages: https://github.com/russHyde/dupree/pull/70 (see https://github.com/russHyde/dupree/pull/72/files for the .html files)

**Comment by patelaryan7751** [comment]
> Do you have any R packages on github? It might make sense to try using pkgdown on one of your own packages first, to find out how it works.
> 
> If it's of interest, these are the changes that running `pkgdown::build_site()` added to one of my packages: [russHyde/dupree#70](https://github.com/russHyde/dupree/pull/70) (see https://github.com/russHyde/dupree/pull/72/files for the .html files)

No currently i have no R packages in my GitHub but i can build a package and try pkgdown. Yes i saw the package and pkgdown implementation.
Just a suggestion can we use GitHub pages or GitHub wiki to build the website?

**Comment by spursbyte** [comment]
can i work on this issue ? @patelaryan7751  do you need any help

**Comment by patelaryan7751** [comment]
> can i work on this issue ? @patelaryan7751  do you need any help

Yes you can work on this issue i am busy with academics . @russHyde has given info on the work  above you can refer to that as well.

**Comment by russHyde** [comment]
Hi @spursbyte . Do you need any help with this issue?

**Comment by spursbyte** [comment]
> Hi @spursbyte . Do you need any help with this issue?

Sure . If you can guide me on how to get started with the issue it will be pretty much helpful.

**Comment by russHyde** [comment]
Have you used pkgdown yet and have you much experience making pull requests etc?

**Comment by spursbyte** [comment]
Yes sure

**Comment by russHyde** [comment]
Ok. Try using pkgdown and we'll see how it looks when you make your pull request.

**Comment by russHyde** [comment]
Hi @spursbyte have you any further questions related to this issue?

**Comment by spursbyte** [comment]
> Hi @spursbyte have you any further questions related to this issue?

Not for now..currently i am working on this issue.if in the process i get some hurdle , I will certainly mention it here.

**Comment by russHyde** [comment]
Hi @spursbyte and @patelaryan7751  , have either of you been working on this? If not , do you need any further help, beyond the stuff I've already posted above?

**Comment by patelaryan7751** [comment]
> Hi @spursbyte and @patelaryan7751 , have either of you been working on this? If not , do you need any further help, beyond the stuff I've already posted above?

hello @russHyde currently we are having exams but it is an assurance from my side we will solve this issue. Ya, if we have any questions we will ask you. If there are any deadlines we will try to finish it before please mention if any .

**Comment by eitsupi** [comment]
Currently lintr is owned by r-lib, I know many of the r-lib's pakages host pkgdown sites on r-lib's domains and using their own templates.
Are r-lib members working on pkgdown site for lintr?
