### ISSUE TITLE
Add `implicit_integer_linter` to our linters?

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#699]
Currently 508 lints in the codebase.
I don't think this should be a default linter, because it is very restrictive.
However, we could use this more strict linter on our code. WDYT?

The fix is to intentionally use `1L` or `1.0` depending on what the data type should be.
Most of our code probably uses integers.

**Comment by MichaelChirico** [comment]
FWIW i have such linter written here already:

https://github.com/Rdatatable/data.table/pull/4278

That said, I don't know what the LICENSE implications are here, maybe best to implement from scratch on `lintr`?

**Comment by AshesITR** [comment]
It already exists?

**Comment by MichaelChirico** [comment]
not as a `Lint`, but the logic to search the XML parse tree & find integer-as-numeric

BTW, I don't know how much it matters for this linter (it can just be turned off if this is a concern?), but long vector support means `x[1]` is probably fine? since the index in general could be double.

**Comment by AshesITR** [comment]
I'm confused.

R/implicit_integer_linter.R exists in lintr already and works, no?

Re `x[1]`: that expression is syntactically equivalent to `x[1L]`. That's why we call it implicit integers. If you truly wanted to index with a double, you'd need to write `x[1.0]`.

**Comment by MichaelChirico** [comment]
Your confusion is well-founded -- I didn't know of that function in `lintr`!

`x[2147483648]` is not syntactically equivalent to `x[2147483648L]`, however (since the latter is `NA_integer_`). That said, I did just check and `x[2147483648]` does not produce a lint, so ignore me :smiley:

**Comment by AshesITR** [comment]
Imo that should lint implicit doubles should be avoided 😄

**Comment by MichaelChirico** [comment]
(BTW, yes, let's add this!)

**Comment by AshesITR** [comment]
This has been done.
