### ISSUE TITLE
[Discussion] Documentation issues

### ISSUE THREAD

**Issue by russHyde** [r-lib/lintr#716]
I'm keen to close down any documentation issues - ideally by updating the docs (README, vignettes and help-pages) - but we should also prune any out-of-date or unreasonable requests.

If anyone sees any issues that are documentation-related, but which don't currently have a documentation label attached, could they label them please.

Additionally, if there are 
- areas of the lintr documentation that need some love 
- ... or that are absent,
- or Q&A/SO posts about lintr that could be answered with better docs,

could you open a new issue. For example, are the lintr options well documented, are there any vignettes that ought to be written, are any of the help-pages out of date...

**Comment by MichaelChirico** [comment]
I think this has been around long enough that we can close & just use the `label:documentation` for pursuing similar bug triage.
