### ISSUE TITLE
reference super-linter

### ISSUE THREAD

**Issue by maxheld83** [r-lib/lintr#766]
https://github.com/github/super-linter wraps a bunch of linters (including lintr) in one workflow and annotates PRs accordingly.

It lints by file type and thus also covers files commonly found in R projects which aren't R (`*.css`, `Dockerfile`, ...).

Perhaps this might be of interest to lintr users, as an alternative to the https://github.com/r-lib/actions lintr action.

I'd be happy to add it to the `README.md` with a PR.

**Comment by AshesITR** [comment]
Thanks for the suggestion. Improving the documentation is always welcome.

**Comment by maxheld83** [comment]
will do once https://github.com/github/super-linter/issues/1232 is resolved; lintr in super-linter is currently too aggressive to be recommended.

**Comment by eitsupi** [comment]
Any update?
The issue seems to be solved.

**Comment by MichaelChirico** [comment]
Closing for now due to inactivity; super-linter still seems pretty active, so please feel free to open a PR directly with the README improvements. Thanks!
