### ISSUE TITLE
Incorporation of custom linter into local lintr package

### ISSUE THREAD

**Issue by ishaar226** [r-lib/lintr#771]
Hi, 
I was wondering where I could find documentation (if there is any) on how to add a custom linter into the existing lintr package default linters for a specific project? That is, how can I add the custom linter to my local lintr package without pushing it to the main lintr repo?

**Comment by AshesITR** [comment]
Is the [creating linters vignette](https://github.com/jimhester/lintr/blob/master/vignettes/creating_linters.Rmd) helpful to you?

**Comment by ishaar226** [comment]
Hi, 
Thank you for the quick response 
I don't think that the vignette talks about the incorporation of custom linters through the creation of a separate package and importing lintr (correct me if I am wrong). Also, I was thinking that if one had to create a separate package to use custom linters , then someone would have posted one of their packages online by now - if that is the case, do you know where I can find someone's custom linter package online?  Since I created another config .lintr file to use for a project (which filters unneeded default linters), should I add my.linters::my_awesome_custom_linter() into that file or the .lintr file for the lintr package.

**Comment by MichaelChirico** [comment]
You might check the reverse imports of `lintr`, e.g. I see a `.lintr` file on `langaugeserver`:

https://github.com/REditorSupport/languageserver/

**Comment by AshesITR** [comment]
> Since I created another config .lintr file to use for a project (which filters unneeded default linters), should I add my.linters::my_awesome_custom_linter() into that file or the .lintr file for the lintr package. 

The project file is the correct place to configure your project-specific linters.
A `.lintr` file in your package would only effect `lintr::lint_package()` for that specific package codebase.

**Comment by ishaar226** [comment]
I'm not exactly sure what the my.linters object is or where it is defined in the `my.linters::my_awesome_custom_linter()`  - and just to clarify, I don't need to build another package to incorporate a custom linter, correct? I can just source the custom linter into the configuration file used in a specific project?

**Comment by AshesITR** [comment]
Oh, sorry, I assumed you would make a package for your custom linter.
Technically, if `my_awesome_custom_linter()` creates a linter and is available in your session (e.g. sourced via `.Rprofile`), you could configure it in the linters using `linters: with_defaults(my_awesome_custom_linter())`.

This would be harder to maintain and keep portable than creating a package though, so I'd really suggest you go the extra mile to create a full package for the linter - it's easier than it seems.
[Hadley's R Packages Book](https://r-pkgs.had.co.nz) is a fine source to get started if you're interested. Packages can easily be installed locally without publishing them anywhere. For personal use it would spare you the hassle of configuring each and every `.Rprofile` and keep your `globalenv()` clean.

**Comment by MichaelChirico** [comment]
I hope the updated vignette is of use to you:

https://lintr.r-lib.org/articles/creating_linters.html

If not, please file a new issue with how else we could improve the documentation.
