### ISSUE TITLE
Add proper benchmarking functionality to .dev/compare_branches.R

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#778]
I think properly benchmarking the two branches is in scope for the script but would require a much bigger PR... filed this quickly as a first pass to give a rough idea (I don't expect it to work for, say, <30% performance difference, but something like 2x/3x should show up)

_Originally posted by @MichaelChirico in https://github.com/jimhester/lintr/issues/777#issuecomment-796612676_

**Comment by kpagacz** [comment]
What would you like to see as a result of benchmarking?

Print microbenchmark results for some examples of each linter?
Allow custom examples - run lintr on a source file?

**Comment by MichaelChirico** [comment]
Nice! Forgot about this issue. Indeed I have in mind to record timings for each linter. It should be fine to track total time spent on each linter over a large enough sample of files.
