### ISSUE TITLE
customise (flycheck-lintr-caching nil)

### ISSUE THREAD

**Issue by yitang** [r-lib/lintr#82]
The solution for #79 provides by @lgatto indicates 

`(flycheck-lintr-caching nil)` 

failed but can be done by `M-x customise-xxxx`

**Comment by jimhester** [comment]
I don't know enough about emacs customization to know what is different between these methods.

**Comment by MichaelChirico** [comment]
No real update here in ~7 years. Closing. Feel free to re-open with a PR to fix.
