### ISSUE TITLE
Polish NEWS

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#833]

**Comment by MichaelChirico** [comment]
TODO: put an item about changes to `default_linters` in the "breaking changes" section at the top

**Comment by MichaelChirico** [comment]
https://github.com/r-lib/lintr/pull/1061#discussion_r851636461

https://github.com/r-lib/lintr/blob/fc6cb377839ffb6862601e72c0e1b86f7ef00015/NEWS.md?plain=1#L11

**Comment by AshesITR** [comment]
TODO explain what flexibility was lost to #1041 (unification of brace related linters)

**Comment by MichaelChirico** [comment]
Leaving this as open for now to force us to take one more pass before release
