### ISSUE TITLE
Does lintr-bot still work for github actions?

### ISSUE THREAD

**Issue by tonyk7440** [r-lib/lintr#854]
Hi,

I have the [lintr workflow](https://github.com/r-lib/actions/blob/master/examples/lint.yaml) in my repo and it runs quite well.
The only thing that is strange is that when an annotation pops up the lintr-bot doesn't comment in the pull request.
Is this still a feature that is working or are there steps to activate it in a repo?

Thanks.

**Comment by MichaelChirico** [comment]
See some discussion on #1558. We recommend imitating this repo's GHA:

https://github.com/r-lib/lintr/blob/bed54c55523e96f7c89154ae31702cd74bb209d8/.github/workflows/lint-changed-files.yaml

It (1) runs `lint_package()` restricted to the files in the `diff` of a given PR (2) the action fails if any new lint is found, and new lints are printed in the `Files` pain inline with where they're found in the source.

**Comment by tonyk7440** [comment]
Ok, thanks all!
