### ISSUE TITLE
linting DESCRIPTION in scope?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#889]
There are a few quality checks we can run on DESCRIPTION files, e.g. to make sure they obey the WRE rules:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

This seems like it could fit in as part of `lint_package()`, any thoughts?

**Comment by AshesITR** [comment]
I think we should keep lintr focused on just linting R code in various contexts.

**Comment by MichaelChirico** [comment]
SGTM!
