### ISSUE TITLE
Setting `error_on_lint: TRUE` causes RStudio session to terminate

### ISSUE THREAD

**Issue by dinakar29** [r-lib/lintr#891]
## Summary

Setting `error_on_lint: TRUE` in the `.lintr` project configurations causes RStudio session to terminate. The issue is consistently reproducible. 

## Details

I was able to create a starter R package, with `hello.R` that looks like this:
 
![Capture1](https://user-images.githubusercontent.com/26552821/145216998-1154430f-6c1d-4e28-9bc0-96180fc819f3.PNG)

And a `.lintr` configuration that looks like this:

![Capture2](https://user-images.githubusercontent.com/26552821/145217004-7f2eea73-48b3-49d2-84da-5bad1d92b5f9.PNG)

Running `lintr::lint("R/hello.R")` led to the R session terminating in RStudio, which led to this:

![image](https://user-images.githubusercontent.com/26552821/145216941-8732ea5c-c36e-4ac5-bc7d-fd63a615e0de.png)

Is this intended behavior? If so, can it be rectified somehow to not cause the session to terminate? Perhaps via different exit status that doesn't cause the session to terminate while also generating an error message with the reason/log pertaining to the lint errors?

#### `sessionInfo()`

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0   
```

#### `packageVersion("lintr")`
```
[1] ‘2.0.1’
```

#### `RStudio.Version()`
```
$citation

To cite RStudio in publications use:

  RStudio Team (2021). RStudio: Integrated Development Environment for R. RStudio,
  PBC, Boston, MA URL http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2021},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.4.1106’

$release_name
[1] "Tiger Daylily"
```

**Comment by AshesITR** [comment]
This behaviour is intentional, but `error_on_lint` is meant for usage in scripts which check the exit code of R after linting. It is not meant to be used interactively.

What are you trying to achieve with this option in RStudio? Maybe there is an alternative approach.

**Comment by AshesITR** [comment]
You can use `options(lintr.error_on_lint = FALSE)` in your Rprofile to manually override the setting in RStudio, or the other way around.
See the new using_lintr vignette in the current GitHub version for details.

**Comment by dinakar29** [comment]
> setting the `LINTR_ERROR_ON_LINT` environment variable here should work with SuperLinter
This worked fine. Will resort to using this instead of the Rprofile or adding the option in the project configuration. Thanks!

**Comment by scottmmjackson** [comment]
I just ran into this in a shared project where someone who doesn't use RStudio for r development set this setting not understanding its consequences.

I feel like `error_on_lint` isn't descriptive of the actual effects of the flag. It doesn't just error on lint, it quits the entire r session and drops a non-standard error code to the console.

I would suggest deprecating the option entirely. I think it's a code smell to decide to terminate the r session from `lint` based on computed configuration state. I better solution might be `lintr::exit_on_error(lintr::lint(...))`.

Apologies if my feedback isn't welcome but I wanted to convey the trouble I was experiencing with this otherwise fantastic package.

**Comment by scottmmjackson** [comment]
I'm also willing to offer a pull request to achieve this if it'd be welcome.
