### ISSUE TITLE
how to silence `no visible global function definition` linter?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#900]
Is there any way for me to silence `no visible global function definition ...` lint by modifying the `.lintr` file?

This lint is so overwhelmingly detected and reported that it's hard to detect any other (maybe more important) lint.

![image](https://user-images.githubusercontent.com/11330453/148380839-568589e7-bbcf-4231-a6d4-7676aa64aa14.png)

**Comment by renkun-ken** [comment]
According to the [documentation](https://github.com/r-lib/lintr#lintr-file-example), you might want to put the following in your `.lintr`:

```
linters: with_defaults(object_usage_linter = NULL)
```

**Comment by IndrajeetPatil** [comment]
Thanks!
