### ISSUE TITLE
Enumerate the "gotchas" mentioned in namespace_hook_linter

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#913]
> Check various common "gotchas" in [.onLoad()], [.onAttach()], [.Last.lib()], and [.onDetach()] namespace hooks that will cause `R CMD check` issues.

this is too vague once the linter will have its own man page, we should enumerate the checks.

**Comment by AshesITR** [comment]
Should probably also link to the base ns-hooks help page.
