### ISSUE TITLE
Create tests for completeness of documentation

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#916]
From https://github.com/AshesITR/lintr/pull/2#discussion_r820162915

> do we have a CRAN release script? we should add something that ensures this list is complete before release in case new tags are added

> Yeah I thought about the possibility to add a test case, but wasn't sure if testthat would be able to reliably inspect the current package help index.
>
> We should also check that all tags have at least one linter, that all tags listed in available_linters() are in fact documented, that all linters listed in available_linters() are exported (and documented) and all exported functions ending in _linter are in available_linters().
>
> Even better would be to check for the Tags & Linters sections where appropriate, to ensure newly created linters have all the necessary boilerplate.

**Comment by jimhester** [comment]
I would suggest using `usethis::use_release_issue()` for tracking any extra tasks needed for a release.

You can add custom tasks by defining a `release_bullets()` function in the package namespace.

e.g. here is the one for usethis itself https://github.com/r-lib/usethis/blob/2402ea8e4eb098b5fd18770174fa86ae1a803658/R/usethis-package.R#L13-L17

**Comment by AshesITR** [comment]
Will this gotcha apply for every release or just those with a modified `release_bullets()`?
