### ISSUE TITLE
Auto-gernerate linter list for README

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#919]
It would be practical to auto-generate the list of available linters in the package README to avoid errors.

An approach to this could be:

1. Make a README.Rmd so we can use R code to generate parts of it
2. Add a single-line description to `linters.csv` (so the CSV structure would be `linter,description,tags`)
3. Use this information in README.Rmd to generate a descriptive list

An added benefit would be that these one-line descriptions could also be put into `?linters`.
In lintr 2.0.1, `?linters` included these one-line descriptions since all linters were `@describeIn`'d there.
The new structure put this information on the individual linter help pages.

WDYT @MichaelChirico, @jimhester?

Alternatively, this could also become a `release_bullet()`, but it would require manual curation without an easily C&P-able template.

**Comment by MichaelChirico** [comment]
I'm not a fan of having a giant wall of text with all the linters in the README. Applying your idea to another top-level file like `linters.Rmd` and then linking to that would work on GitHub but I think not on CRAN. Maybe a pkgdown article instead (is that a thing?) and link to that?

**Comment by AshesITR** [comment]
pkgdown can automatically create articles from vignettes IIRC.
We could then link to the pkgdown site from README.md

**Comment by MichaelChirico** [comment]
right... feels like a bit of a kludge though. e.g. do we want a vignette listed on CRAN that's not really a vignette but an index of linters?

I was wondering if there's a way besides vignettes to add articles manually

**Comment by AshesITR** [comment]
Looks like a [no](https://pkgdown.r-lib.org/reference/build_articles.html) at first glance.

**Comment by AshesITR** [comment]
An admittedly hacky way to keep a vignette out of CRANs sight would be to modify `.Rbuildignore`, right?

**Comment by MichaelChirico** [comment]
Looks like `usethis::use_article()` is what we want. IIUC it's implemented as basically the same as your suggestion TBH 😅 

https://usethis.r-lib.org/reference/use_vignette.html

**Comment by AshesITR** [comment]
Nice find. It does in fact do that, but also moves aricles to `vignettes/articles` for clarity.
Looks like the way to go then.

**Comment by AshesITR** [comment]
Related: #691

**Comment by MichaelChirico** [comment]
🙈 somehow i thought we have one already

**Comment by MichaelChirico** [comment]
We might want to punt on this one, unless we plan to bundle the new pkgdown site with the 3.0.0 release.

**Comment by AshesITR** [comment]
Agreed. Let's defer since this isn't strictly release dependent anyway.
