### ISSUE TITLE
withr 2.5.0 dependency

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#925]
Just realized that `lines=` is a new argument as of 2.5.0:

https://github.com/r-lib/lintr/blob/4148ebdf8a39050e79b5b519c56de3bbc09c797b/tests/testthat/test-rstudio_markers.R#L91

Are we fine adding a 2.5.0 version dep on `withr`? It's pretty easy to replace with "old" withr functionality, but still a pretty convenient feature, and IIUC package version deps aren't as tough to comply with as R version deps.

**Comment by AshesITR** [comment]
Don't we already use some `tempfile()` and `writeLines()` code in other tests?

Also, how old is wothr 2.5.0?

**Comment by MichaelChirico** [comment]
> Don't we already use some tempfile() and writeLines() code in other tests?

Almost surely. Nothing stopping us from replacing that with `lines=` as well :)

> how old is withr 2.5.0?

9 days :) but we won't be releasing to CRAN for some time, I'd reckon.

**Comment by AshesITR** [comment]
I'd rather not depend on such a recent version.
