### ISSUE TITLE
Add `allow_multiple_spaces = TRUE` to `infix_spaces_linter()` to fully replace `assignment_linter()`

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#940]
Since @f-ritter's original use-case was disallowing these, I think we should also support that rule via an argument (`allow_multiple_spaces = TRUE`). WDYT?

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/931#r826186757_

NB: The implementation will likely be easier using XPath instead of `ids_with_token`.

**Comment by MichaelChirico** [comment]
Copying comment from the thread too:

> should be a lot easier if we convert the linter to XPath at the same time (requires something like following-sibling::*[@col1 = preceding-sibling::*/@col2] vs. > preceding-sibling::*/@col2 iinm)

**Comment by MichaelChirico** [comment]
NB: be sure to offer attribution for this fix when this is filed. The following was lost in #931

> New `assignment_spaces()` lintr. (#538, @f-ritter)
