### ISSUE TITLE
tags= argument for available_linters()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#980]
As well as filtering by `package`, it would be helpful to run `available_linters(tags = "package_development")` and receive all the rows associated with `package_development` linters

**Comment by AshesITR** [comment]
This could be used in `rd_linters(tag)` as well.

**Comment by AshesITR** [comment]
Could also be accompanied by a factory `with_tags(..., tags = "default", packages = "lintr")` that would construct a linter list from the results WDYT?

The interface would be the same as `with_defaults()` but it would be easier to enable many linters.

Might even be worth to add `with_all_linters(..., package = "lintr")` as an easy way to try them all?
