### ISSUE TITLE
Add `{lintr}` hex sticker?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#981]
I love talking about `{lintr}`, but I always find it a tad bit dissatisfying to have slides with just the name of the package without a cool hex sticker to go along with it! 🙃

I wish I were creative enough to design and contribute one, but maybe this can be crowdsourced (on Twitter, e.g.)?

Thanks for the awesome work, either way! Looking forward to the `3.0.0` release.

**Comment by AshesITR** [comment]
If created, this could also be featured here:
https://github.com/GuangchuangYu/hexSticker

**Comment by MichaelChirico** [comment]
marking this one as duplicate

**Comment by IndrajeetPatil** [comment]
Closed in favour of https://github.com/r-lib/lintr/issues/1188
