### ISSUE TITLE
Produce SARIF reports ?

### ISSUE THREAD

**Issue by nvuillam** [r-lib/lintr#991]
V6 version of [MegaLinter](https://megalinter.github.io/) (currently in development) will support [SARIF](https://sarifweb.azurewebsites.net/) format, which is standard for SAST tools (cf https://megalinter.github.io/v6-alpha/supported-linters/ )

It would help a lot with the integration if your great R linter was able to provide SARIF output, is it something you would like to consider ?

Thanks :)

**Comment by MichaelChirico** [comment]
The standard is ~300 pages long :)

https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.pdf

Happy to take PRs providing a conversion function. For now I'm not particularly keen to write anything myself.

**Comment by nvuillam** [comment]
Nobody ever read it, just looking at the examples is enough to implement
the output JSON format:)

About the PR, unfortunately i don't have any experience in R :/

Le jeu. 24 mars 2022 à 00:08, Michael Chirico ***@***.***> a
écrit :

**Comment by AshesITR** [comment]
This is an example JSON for a single (!) lint, for anyone interested in writing a PR for this. It's from Page 211 of the standard.

```json
  {
  "version": "2.1.0",
  "runs": [
{
"tool": {
        "driver": {
          "name": "CodeScanner",
          "rules": [
            {
              "id": "C2001",
              "fullDescription": {
"text": "A variable was used without being initialized. This can result in runtime errors such as null reference exceptions."
              },
              "messageStrings": {
"default": {
"text": "Variable \"{0}\" was used without being initialized."
 } }
} ]
} },
"artifacts": [
  {
"location": {
"uri": "src/collections/list.cpp", "uriBaseId": "SRCROOT"
},
    "sourceLanguage": "c"
  }
],
"results": [
  {
    "ruleId": "C2001",
    "ruleIndex": 0,
          "message": {
            "id": "default",
            "arguments": [
"count" ]
          },
          "locations": [
            {
              "physicalLocation": {
"artifactLocation": {
"uri": "src/collections/list.cpp", "uriBaseId": "SRCROOT",
"index": 0
                },
                "region": {
                  "startLine": 15
                }
              },
              "logicalLocations": [
{
"fullyQualifiedName": "collections::list::add"
} ]
} ]
} ]
} ]
}
```

**Comment by nvuillam** [comment]
There is a repo full of examples -> https://github.com/microsoft/sarif-tutorials/blob/main/samples/1-Introduction/simple-example.sarif

By basically, this is:
- list of errors
- lit of results
and a result is:
- file
- position (start line, start char, end line, end char )
- error message

The SARIF spec has been builtto manage all cases of the universe, but for usual linters it's not that complicated , and most of properties are optional^^

**Comment by shaopeng-gh** [comment]
Hello everyone, I am late to the party. :)
I am from SARIF team working on seeking adding SARIF support for top linters for each languages.
I will be working on code changes in this repo to support option to output as SARIF format,
and after this is done creating a starter workflow in the GitHub starter workflow repo to make it available as a GitHub code scanner.

previous linters I worked on the command line mostly look like below:
`lintername targetdir --format=default|json|xml`
If the linter already have the format option we will be adding sarif to the accept list.
if the linter does not have the parameter and only have 1 format, we will ask the tool owner preference.

should I add a parameter called "format", and accept "default" or "sarif"

( I have not work on R language and the lintr tool before, feel free to let me know if have any guidance, thanks! )

**Comment by AshesITR** [comment]
Hi, you can check the `checkstyle_output()` function for output in a non-default format.
Invocation via the command line would be something like

```sh
R -e "lintr::checkstyle_output(lintr::lint_package(path = '.'), filename = 'output_file.xml')"
```

**Comment by shaopeng-gh** [comment]
this is a great info, thanks!
So now I am not looking to add a parameter for format, I can copycat and follow the checkstyle_output to create a sarif_output:
```
R -e 'lintr::checkstyle_output(lintr::lint_dir("."), "checkstyle-result.xml")'  
R -e 'lintr::sarif_output(lintr::lint_dir("."), "sarif-result.xml")'
```
