### ISSUE TITLE
Combine all paste linters

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#998]
let's think about it in an issue. there are a few paste-related linters incoming. as I was writing this PR I thought it might make sense to merge them all into just one paste_linter.

another thing I see sometimes that I'd like to lint is paste0(x, collapse=). if there's only one input it's the same as the paste version, but it'd be nice to be consistent and the paste0 looks a bit distracting/misleading to me

__Originally posted by @MichaelChirico in https://github.com/r-lib/lintr/pull/997#discussion_r835576040__

**Comment by AshesITR** [comment]
The `toString()` lint could also point to `glue::glue_collapse()` in its message in case the actual intention is to create a human friendly enumeration.

**Comment by MichaelChirico** [comment]
Closing here; tracking the rest in #1108 after release
